### ISSUE TITLE
`v error` on comparing byte array with byte array

### ISSUE THREAD

**Issue by popzxc** [vlang/v#2422]
**V version:** V 0.1.21 6890034
**OS:** Linux Mint 19

**What did you do?**
Compared byte array with byte array

```v
fn test_something() {
    mut all_possible_bytes := []byte
    mut i := 0
    for i < 256 {
        all_possible_bytes << byte(i)
        i += 1
    }

    assert all_possible_bytes == all_possible_bytes
}
```

**What did you expect to see?**
Not sure, but since there was "This should never happen" in output, I guess not that :)
 
**What did you see instead?**
```sh
`/home/example/example/example_test.v`
 (
/home/example/example/example_test.tmp.c:5228: error: operation on a struct
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
)
----------------------------------------------------------------------------
    51 ms | <=== total time spent running V _test.v files 
 ok, fail, total =     0,     1,     1
```

**Comment by HoLLy-HaCKeR** [comment]
Encountered this too, can be reproduced with `_ = ([byte(0x00)] == [byte(0x00)])`.

Generated C code:
```c
 void main__main() {
 
 (new_array_from_c_array(1, 1, sizeof(byte), EMPTY_ARRAY_OF_ELEMS( byte, 1 ) {  ((byte)( 0x00 ) )  }) ==new_array_from_c_array(1, 1, sizeof(byte), EMPTY_ARRAY_OF_ELEMS( byte, 1 ) {  ((byte)( 0x00 ) )  }) ) ; ;
 
 }
```

**Comment by ka-weihe** [comment]
Works in V 0.1.26 50a8373.71a92eb.
