### PR TITLE
pref: Give user the ability to specify the default c compiler to use

### PR DESCRIPTION
**Pull request by programmingkidx**
Currently v picks the default compiler to use. For Mac OS it uses /usr/bin/cc. This compiler might be good. Then again it could be old and not meeting v's requirements. The user might also want to compare performance differences between different c compilers. To be able to do this the user needs to be able to specify the default c compiler used by v. This pull request gives the user to do this by setting the use_c_compiler flag to the name of the desired compiler. Then add that flag to the VFLAGS variable.

Here is an example of how to build v using this flag: 
VFLAGS="-d use_c_compiler=clang-mp-3.8" make

### CODE REVIEW

**Comment by JalonSolov** [comment]
Rather than modify V itself, (since the `-cc` option works fine), why not modify the GNUMakefile so you can just do `make -clang-mp-3.8` or perhaps better, `make -cc clang-mp-3.8` instead of having to modify VFLAGS?

**Comment by programmingkidx** [comment]
Well on Mac OS 10.4 V uses /usr/bin/cc when using the REPL. This is a link to gcc-4.0. This compiler is pretty old and does not implement the C11 standard that v requires. So without these changes running ./v would always display an error message. Having v use a newer compiler makes the REPL work on Mac OS 10.4.

**Comment by programmingkidx** [comment]
Would also like to note that trying to use the REPL like this still produces an error: ./v -cc clang-mp-3.8

**Comment by JalonSolov** [comment]
@medvednikov what do you think?

**Comment by JalonSolov** [comment]
You should also be able to do
```
VFLAGS="-cc clang-mp-3.8" make
```
without modifying V.  And if you want the REPL to use the same, you can either do
```
VFLAGS="-cc clang-mp-3.8" v
```
or
```
export VFLAGS="-cc clang-mp-3.8"
```
if you don't care about it always being slower than it would be with tcc.

**Comment by programmingkidx** [comment]
Trying 'VFLAGS="-cc clang-mp-3.8" ./v' did work. But there is the convenience factor to consider. The user only has to specify the compiler once if using the way this pull request implements. Doing it the way you mention is not very well known or documented yet.

**Comment by medvednikov** [comment]
We have a one way policy.

VFLAGS works and is documented in docs.md:

image

This new way would have to be documented too, and we'd have 2 ways to do the same thing.
