### ISSUE TITLE
Incorrect typing on array of maps in function params

### ISSUE THREAD

**Issue by twisterghost** [vlang/v#3946]
**V version:** V 0.1.25 5142747
**OS:** macOS 10.14.6

**What did you do?**

Maybe this is just a limitation of maps/arrays, but I haven't found anything in docs or issues.

When specifying a function parameter of type `[]map[string]int`, it gets interpreted as just a map. Here is a contrived example:

```V
module main

fn first(input []map[string]int) map[string]int {
  if input.len == 0 {
    return 0
  }

  return input[0]
}

fn main() {
  stuff := [
    {
      'hello': 0,
      'foo': 1
    },
    {
      'hello': 2,
      'foo': 5
    },
  ]

  println(stuff[0]['hello'])
  println(first(stuff)['hello'])
}
```

Outputs:

**What did you expect to see?**

Expected to compile and run. The same function but with a `[]int` argument works.

 
**What did you see instead?**

```
./demo.v:4:14: type `map_int` has no field or method `len`
    2|
    3| fn first(input []map[string]int) map[string]int {
    4|   if input.len == 0 {
                    ^
    5|     return {}
    6|   }
```

**Comment by alexesprit** [comment]
This example is not correct. You cannot return an integer in the `first` function.

The new backend shows a proper error, though:
```
$ vrun test4.v
test4.v:6:3: error: cannot use `int` as type `map_string_int` in return argument 
    4|   if input.len == 0 {
    5|     return 0
    6|   }
         ^
    7|
    8|   return input[0]
```

The correct example is:
```v
module main

fn first(input []map_string_int) map[string]int {
	if input.len == 0 {
		return map[string]int
	}
	return input[0]
}

fn main() {
	stuff := [{
		'hello': 0
		'foo': 1
	}, {
		'hello': 2
		'foo': 5
	}]
	println(stuff[0]['hello'])
	println(first(stuff)['foo'])
}
```
and it works fine.
```
$ vrun test4.v
0
1
```

**Comment by twisterghost** [comment]
Thanks for the update - though I'm trying to figure out how the code in the example was changed to have `return 0` - I must've typed that by accident when transcribing. The pasted error below shows what the line was supposed to read as, which was `return {}`.

Does this still hold true for the corrected snippet? It was supposed to be...

```v
module main

fn first(input []map[string]int) map[string]int {
  if input.len == 0 {
    return {}
  }

  return input[0]
}

fn main() {
  stuff := [
    {
      'hello': 0,
      'foo': 1
    },
    {
      'hello': 2,
      'foo': 5
    },
  ]

  println(stuff[0]['hello'])
  println(first(stuff)['hello'])
}```

**Comment by alexesprit** [comment]
It works fine in V 0.1.26 182108f for the corrected example, where `return {}` used.

```
$ vrun test4.v
0
0
```

> but I'm assuming that just means this will be fixed with the new backend?

It's already fixed, but is not released yet.

**Comment by twisterghost** [comment]
Gotcha. Thanks!
