### ISSUE TITLE
Interface crashes app at start

### ISSUE THREAD

**Issue by anihex** [vlang/v#3905]
**V version:** V 0.1.25 8497d63
**OS:** Kubuntu 18.04

**What did you do?**

I worked on a _small_ game engine that uses 'Scenes' to organize it's content. Those 'Scenes' are defined by an Interface ('Scener'). The 'Game' struct holds a map of those 'Scenes'. They can be added and then switched to by using it's name.

There are **2** examples.

**example 1**  
I made a simple demo containing nothing but an empty title screen.

```v
// --- vaser.game.v ---

// Game holds all data of the game. The assets, the scenes and the graphics
// context
pub struct Game {
mut:
	gg            &gg.GG
	ft            &freetype.FreeType
	images        map[string]Image
	is_running    bool
	scenes        map[string]Scener // <---
	current_scene string
}

// new creates a new Instance of Game. It initilises GLFW, opens the window and
// it also flips the loaded images if need be.
pub fn new(w, h int, title string, flip_image bool) &Game {
	glfw.init_glfw()
	stbi.set_flip_vertically_on_load(flip_image)
	mut game := &Game{
		gg: gg.new_context(gg.Cfg{
			width: w
			height: h
			use_ortho: true
			create_window: true
			window_title: title
			window_user_ptr: 0
		})
		ft: freetype.new_context(gg.Cfg{
			width: w
			height: h
			use_ortho: true
			font_size: 18
			scale: 2
			window_user_ptr: 0
		})
		images: map[string]Image
		scenes: map[string]Scener
		is_running: true
	}
	game.gg.window.set_user_ptr(game)
	game.gg.window.onkeydown(key_down)
	return game
}

// add_scene adds a new scene to the game. The key allows for an easy switch to
// different scenes.
pub fn (game mut Game) add_scene(key string, scene Scener) {
	if game.current_scene == '' {
		game.current_scene = key
	}
	game.scenes[key] = scene
}
```

```v
// --- vaser.scener.v ---

// Scener is a simply interface of what a scene for the game has to implement.
// Structs that implement this interface can be added to the scene collection.
interface Scener {
	// create is called before the game switches to the scene. The scene can
	// prepare it's content here.
	create()
	// input got the same parameters the glfw callback gets. That is, without
	// the wnd value
	input (string)
	// update is called everytime shortly before the scene is rendered.
	update()
	// render is called after the scene was updated.
	render()
	// exit is used to free ressources. It is called, when the scene is unloaded.
	// This happens, when the game switches and the "reset-scene" was true.
	exit  ()
	// keys returns an array of keybindings. Only keys that match the content
	// trigger the input handler.
	keys  ()[]KeyMap
}
```

```
// --- main.v ---

fn main() {
	mut game := vaser.new(640, 480, 'Vlang - The Game', true)
	game.add_scene('title', Title{game: game})
	game.run()
}
```

```v
// --- title.v ---

// Title is the title-screen. It shows the title-background and the options the
// player can pick. Depending on what the player selects, the game switches to
// a different scene.
struct Title {
pub mut:
	game &vaser.Game
}

fn (scene &Title) create() {
	println('title.create')
}

fn (scene &Title) input(key string) {
	println('title.input; key: ${key}')
}

fn (scene &Title) update() {
	println('title.update')
}

fn (scene &Title) render() {
	//
}

fn (scene &Title) exit() {
	println('title.exit')
}

fn (scene &Title) keys() []vaser.KeyMap {
	return [{
		key: vaser.KEY_LEFT
		name: 'LEFT'
	},
	{
		key: vaser.KEY_RIGHT
		name: 'RIGHT'
	},
	{
		key: vaser.KEY_DOWN
		name: 'DOWN'
	},
	{
		key: vaser.KEY_UP
		name: 'UP'
	}
	]
}
```

**example 2**

This one is a bit more compact:

```v
module main

interface Meower {
	meow()
}

struct Animals {
mut:
	meows map[string]Meower
}

fn new_animals() &Animals {
	a := &Animals{
		meows: map[string]Meower
	}
	
	return a
}

fn (a mut Animals) add_meow(name string, meow Meower) {
	a.meows[name] = meow
}

fn main() {
	mut zoo := new_animals()
	zoo.add_meow('cat', new_cat('Tigga'))
}

fn new_cat(name string) Meower {
	return Cat{name: name}
}

struct Cat {
	name string
}

fn (c &Cat) meow() {
	println('Meow! ${c.name} says MEOW!')
}
```

**What did you expect to see?**

In _example 1_ I expected to see a Window that shows an image (image drawing was removed from code). In Version 99cbc58db8b8bf00b665f8ac864da5dbec52f3dc, this worked as expected.

In _example 2_ I expected it to run and then quit without ever writing something. This *did not* work in Version 99cbc58db8b8bf00b665f8ac864da5dbec52f3dc.
 
**What did you see instead?**
Both crash without ever opening a window. The error message (short) is:

example 1
```
incompatible type for argument 3 of ‘anihex_dot_vaser__Game_add_scene’
  anihex_dot_vaser__Game_add_scene ( game ,  tos3("title") , (Title) { .game = 
```

example 2
```
incompatible types when returning type ‘Cat {aka struct Cat}’ but ‘Meower {aka struct Meower}’ was expected
 return  (Cat) { .name =  name } ;
```

example 1 stopped working since a678be71951d6fb24afa0a15bb7d9a6db58033cb
