### ISSUE TITLE
Weekly 2024.18 does not build on Mac Sonoma 14.4.1

### ISSUE THREAD

**Issue by mike-ward** [vlang/v#21383]
### Describe the bug

Run `v up` on Mac Sonoma 14.4.1

The error below occurs:

```
v up
Updating V...
Found `make` as `/usr/bin/make`.
Found `cc` as `/usr/bin/cc`.
> make failed:
> make output:
cd ./vc && git clean -xf && git pull --quiet
cd ./thirdparty/tcc && git clean -xf && git pull --quiet
cc  -std=gnu99 -w -o v1.exe ./vc/v.c -lm -lpthread
./v1.exe -no-parallel -o v2.exe  cmd/v
vlib/v/pref/pref.c.v:405:9: error: undefined ident: `current_args`
  403 |                 if command_pos == -1 {
  404 |                     // Version flags after a command are intended for the command, not for V itself.
  405 |                     if current_args.len > 1 && arg == '-v' {
      |                        ~~~~~~~~~~~~
  406 |                         // With additional args after the `-v` flag, it toggles verbosity, like Clang.
  407 |                         // E.g.: `v -v` VS `v -v run examples/hello_world.v`.
vlib/v/pref/pref.c.v:405:22: error: `current_args` does not return a value
  403 |                 if command_pos == -1 {
  404 |                     // Version flags after a command are intended for the command, not for V itself.
  405 |                     if current_args.len > 1 && arg == '-v' {
      |                                     ~~~
  406 |                         // With additional args after the `-v` flag, it toggles verbosity, like Clang.
  407 |                         // E.g.: `v -v` VS `v -v run examples/hello_world.v`.
vlib/v/pref/pref.c.v:405:22: error: left operand for `&&` is not a boolean
  403 |                 if command_pos == -1 {
  404 |                     // Version flags after a command are intended for the command, not for V itself.
  405 |                     if current_args.len > 1 && arg == '-v' {
      |                                     ~~~~~~~
  406 |                         // With additional args after the `-v` flag, it toggles verbosity, like Clang.
  407 |                         // E.g.: `v -v` VS `v -v run examples/hello_world.v`.
vlib/v/pref/pref.c.v:405:22: error: non-bool type `void` used as if condition
  403 |                 if command_pos == -1 {
  404 |                     // Version flags after a command are intended for the command, not for V itself.
  405 |                     if current_args.len > 1 && arg == '-v' {
      |                                     ~~~~~~~~~~~~~~~~~~~~~~
  406 |                         // With additional args after the `-v` flag, it toggles verbosity, like Clang.
  407 |                         // E.g.: `v -v` VS `v -v run examples/hello_world.v`.
make: *** [all] Error 1

Current V version: V 0.4.5 1aee2b5, timestamp: 2024-04-24 19:23:19 +0300
Recompiling V *failed*.
Found `make` as `/usr/bin/make`.
Found `cc` as `/usr/bin/cc`.
Try running `make` .```

### Reproduction Steps

v up

### Expected Behavior

New build completes

### Current Behavior

Error occurred compiling update.

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### V version

V 0.4.5 1aee2b5

### Environment details (OS name and version, etc.)

Mac Book Air M2, 8GB, Sonoma 14.4.1
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by ttytm** [comment]
Hey @mike-ward. I see that building issue you encountered. There was a conflicting change which resulted in that issue you are reporting about. A fix was pushed shortly after. I'm on macOS 14.4.1 and things work again on this end. Can you please try again?

It's less an issue with the state at the weekly tag but with the commit that was tried to be updated to.

**Comment by mike-ward** [comment]
Works now. Thanks!

Now if only we could get a working build of Ved 😄
