### ISSUE TITLE
Example apps fail to compile on MacOS BigSur 11.6

### ISSUE THREAD

**Issue by jeffmikels** [vlang/v#12989]
**V doctor:**
```
OS: macos, macOS, 11.6, 20G165
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
CC version: Apple clang version 12.0.5 (clang-1205.0.22.11)

getwd: /Users/jeff/src/v/examples
vmodules: /Users/jeff/.vmodules
vroot: /Users/jeff/src/v
vexe: /Users/jeff/src/v/v
vexe mtime: 2021-12-29 02:19:20
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 43fee6b.5e55294

Git version: git version 2.32.0
Git vroot status: weekly.2021.52.1-3-g5e552944
.git/config present: true
thirdparty/tcc status: thirdparty-macos-amd64 93fa86be

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg tetris/tetris.v`
See attached file `tetris/tetris.v`

**What did you expect to see?**

The Tetris example app

**What did you see instead?**
```
==================
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

```

**Comment by jeffmikels** [comment]
I resolved my issue by downloading the binary of v `0.2.4` instead of running `v up`
