### ISSUE TITLE
V 0.5.2  error: unexpected token `@`, expecting name

### ISSUE THREAD

**Issue by kostya** [vlang/v#28074]
### Describe the bug

after update from 0.5.1 to 0.5.2 got this error, reproduced on linux and macOS arm64.

### Reproduction Steps

```
git clone https://github.com/kostya/LangArena.git
cd LangArena/v
v -enable-globals -gc boehm -o target/bin_v_gcc_debug .
```

### Expected Behavior

compiled

### Current Behavior

```
v -enable-globals -gc boehm -o target/bin_v_gcc_debug .

calculator.v:3:1: error: unexpected token `@`, expecting name
    1 | module calculator
    2 |
    3 | import benchmark
      | ^
    4 | import helper
    5 | import strings
maze.v:3:1: error: unexpected token `@`, expecting name
    1 | module mazebench
    2 |
    3 | import benchmark
      | ^
    4 | import helper
    5 | import math
```

### V version

V 0.5.2 7647ce1

### Environment details (OS name and version, etc.)

macOS arm64
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.
