### PR TITLE
examples: reorganize examples

### PR DESCRIPTION
**Pull request by alexesprit**
## Changelog

* Added missing entries to .gitignore files.
* Added missing .gitignore files.
* Formatted examples.
* Moved `sqlite` example to `database` directory.
* Moved gg examples to `gg` directory.
* Renamed `sokol_examples` directory to `sokol`.

### CODE REVIEW

**Comment by medvednikov** [comment]
mingw: ```vc\v_win.c:14375:36: error: storage size of 'info' isn't known
         CONSOLE_SCREEN_BUFFER_INFO info;```

**Comment by alexesprit** [comment]
It's due to 0f1f724a916bf78ca73ee3002fa71eb96e516ff6 changes. There're two recent `windows-msvc` and `windows-gcc` jobs complete w/o errors.

**Comment by medvednikov** [comment]
It was reverted.

**Comment by alexesprit** [comment]
GitHub doesn't remove, but keeps a list of previous jobs (two of them were failed due to 0f1f724 changes) after PR close/reopen. There're two other recent `windows-msvc` and `windows-gcc` jobs complete w/o errors.
