### ISSUE TITLE
cgen error struct or union expected

### ISSUE THREAD

**Issue by einar-hjortdal** [vlang/v#26837]
### Describe the bug

cgen error

### Reproduction Steps

```
git clone https://github.com/einar-hjortdal/redict.git
cd redict
git checkout fa7cc503a19aea6ed6b5a8c7c78e93fdcae5ca28
v run options_test.v
```

### Expected Behavior

no error

### Current Behavior

```
================== C compilation error (from tcc): ==============
cc: /tmp/v_1000/options_test.01KNGTXNPGBZK596A2TE03K616.tmp.c:19666: error: struct or union expected
=================================================================
```

### Additional Information/Context

Regression: worked fine in V 0.5.0 162a6e9

### V version

V 0.5.1 046ae4f

### Environment details (OS name and version, etc.)

|V full version      |V 0.5.1 58f18573557247e9c743f7d60e5b3ab783f74479.046ae4f
|:-------------------|:-------------------
|OS                  |linux, "openmamba release 2026.3 for x86_64 (rolling)"
|Processor           |8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
|Memory              |17.58GB/31.17GB
|                    |
|V executable        |/home/einar/.local/lib64/v/v
|V last modified time|2026-04-06 05:34:06
|                    |
|V home dir          |OK, value: /home/einar/.local/lib64/v
|VMODULES            |OK, value: /home/einar/.vmodules
|VTMP                |OK, value: /tmp/v_1000
|Current working dir |OK, value: /home/einar/Documents/projects/vlang/active/redict
|                    |
|Git version         |git version 2.53.0
|V git status        |weekly.2026.03-829-g046ae4fb
|.git/config present |true
|                    |
|cc version          |cc (GCC) 15.2.1 20251019
|gcc version         |gcc (GCC) 15.2.1 20251019
|clang version       |N/A
|tcc version         |tcc version 0.9.28rc 2025-02-13 HEAD@f8bd136d (x86_64 Linux)
|tcc git status      |thirdparty-linux-amd64 696c1d84
|emcc version        |N/A
|glibc version       |ldd (GNU libc) 2.43
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by einar-hjortdal** [comment]
Minimal repro found
```v
module main

interface Value {}

fn get_string_value() Value {
	return 'bro'
}

fn main() {
	s := get_string_value()
	match s {
		string {
			if s.len < 4 || (s.len >= 4 && s[3] != `:`) {
				panic("Can't parse verbatim string reply")
			}
			println(s[4..])
		}
		else {
			panic('unexpected in repro')
		}
	}
}
```
