### ISSUE TITLE
V fails to compile on Termux

### ISSUE THREAD

**Issue by EmiyaSyahriel** [vlang/v#25121]
### Describe the bug

Seems like the compiler ( all of the `v1`, `v2 `and `v` ) generates an invalid conditional check on termux : 
```
#if defined __BIONIC_AVAILABILITY_GUARD && __BIONIC_AVAILABILITY_GUARD(28)
```
at https://github.com/vlang/v/blob/a88df9193833285eb056f5ab207d716e8a727c1b/vlib/v/gen/c/cheaders.v#L340 and https://github.com/vlang/vc/blob/7ff4c995b93b975631c9f472ef64c7e7451f18af/v.c#L858

I don't know if this line is actually valid in C, but this fails to compile on tcc ( 0.9.27 ) and clang ( 20.1.5 ). 

### Reproduction Steps

In Termux, clone the repo, and then compile it from scratch using `make`. Or if you have an existing `v` installation, just call `v up`

### Expected Behavior

V compiles and runnable

### Current Behavior

Compilation fails with this compilation error : 
```
./vc/v.c:858:44: error: function-like macro '__BIONIC_AVAILABILITY_GUARD' is not defined                                              858 | #if defined __BIONIC_AVAILABILITY_GUARD && __BIONIC_AVAILABILITY_GUARD(28)
```

### Possible Solution

I was able to compile it by patching the statement in both `vc/v.c` and the generator `vlib/v/gen/c/cheaders.v` with this workaround :
```c
#ifdef __TERMUX__
  #if defined(__BIONIC_AVAILABILITY_GUARD)
    #if __BIONIC_AVAILABILITY_GUARD(28)
    #else
    void * aligned_alloc(size_t alignment, size_t size) { return malloc(size); }
    #endif
  #else
  void * aligned_alloc(size_t alignment, size_t size) { return malloc(size); }
  #endif
#endif
```
But this is just a crude monkey patch with inefficient code structure and without further testing for it's side effect on programs compiled with the compiler containing this workaround, so I'm afraid to make this into a PR, someone might be able to figure out a more efficient code structure ( no duplicate of the `aligned_alloc` )

### Additional Information/Context

Futher generated infos such as `v version` and `v doctor` were all from the binary I successfully compiled with the workaround.

### V version

V 0.4.11 a88df91

### Environment details (OS name and version, etc.)

|V full version      |V 0.4.11 a88df9193833285eb056f5ab207d716e8a727c1b
|:-------------------|:-------------------
|OS                  |termux, 5.4.254-qgki-gf7c97dba22cd, # 1 SMP PREEMPT Fri Jul 4 07:19:18 UTC 2025
|Processor           |8 cpus, 64bit, little endian
|Memory              |N/A
|                    |
|V executable        |/data/data/com.termux/files/home/build/v/v
|V last modified time|2025-08-16 18:36:46
|                    |
|V home dir          |OK, value: /data/data/com.termux/files/home/build/v
|VMODULES            |OK, value: /data/data/com.termux/files/home/.vmodules
|VTMP                |OK, value: /data/data/com.termux/files/usr/tmp/v_10282
|Current working dir |OK, value: /data/data/com.termux/files/home/build/v
|                    |
|Git version         |git version 2.49.0
|V git status        |weekly.2025.33-43-ga88df919-dirty
|.git/config present |true
|                    |
|cc version          |clang version 20.1.5
|gcc version         |clang version 20.1.5
|clang version       |clang version 20.1.5
|tcc version         |N/A
|tcc git status      |thirdparty-unknown-unknown de82a130
|emcc version        |N/A
|glibc version       |readelf: Error: 'readlink (GNU coreutils) 9.6
- system tcc version : 0.9.27 HEAD:6a24b762 2023-04-15T15:36:13+02:00 locally modified (AArch64 Linux)
- device : Nokia X30 5G ( Android 14 )

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by gechandesu** [comment]
Compiled successfully for me after upgrading termux packages (via `pkg upgrade`), `clang` is upgraded to `20.1.8`.

<details><summary>v doctor</summary>
<p>

|V full version      |V 0.4.11 bbb61ab3687afe512a1fa12492c876d011626107.a88df91
|:-------------------|:-------------------
|OS                  |termux, 5.10.226-android12-9-00051-ga13323220e07-ab12931418, #1 SMP PREEMPT Thu Jan 16 10:38:32 UTC 2025
|Processor           |8 cpus, 64bit, little endian
|Memory              |N/A
|                    |
|V executable        |/data/data/com.termux/files/home/.vlang/v
|V last modified time|2025-08-16 21:14:20
|                    |
|V home dir          |OK, value: /data/data/com.termux/files/home/.vlang
|VMODULES            |OK, value: /data/data/com.termux/files/home/.vmodules
|VTMP                |OK, value: /data/data/com.termux/files/usr/tmp/v_10231
|Current working dir |OK, value: /data/data/com.termux/files/home
|                    |
|Git version         |git version 2.50.1
|V git status        |a88df919
|.git/config present |true
|                    |
|cc version          |clang version 20.1.8
|gcc version         |clang version 20.1.8
|clang version       |clang version 20.1.8
|tcc version         |N/A
|tcc git status      |thirdparty-unknown-unknown de82a130
|emcc version        |N/A
|glibc version       |readelf: Error: 'readlink (GNU coreutils) 9.7

</p>
</details>

**Comment by EmiyaSyahriel** [comment]
@gechandesu You're right, I upgraded Clang to 20.1.8 and it did compile. I thought 20.1.5 was recent enough because it released just like 2 months ago 😅.

But then, why the `#if defined __BIONIC_AVAILABILITY_GUARD` part being in the same line, if it still made the `__BIONIC_AVAILABILITY_GUARD(28)` part won't compile because it wasn't defined anyway? Or is it just a non-recent C compiler's issue?

Anyway, I will close this issue then since it is easily fixable by upgrading the C compiler, thank you.
