### ISSUE TITLE
Regression in V 0.5.2: False positive interface implementation error on method with function parameter

### ISSUE THREAD

**Issue by filipos800** [vlang/v#28042]
### Describe the bug

After upgrading from V 0.5.1 to 0.5.2, compiling existing code that worked correctly now fails with a compiler error stating that a struct incorrectly implements an interface method.

The error is confusing because the compiler complains about parameter 3 being a function type (fn (core.IEventData)), yet both the interface definition and the struct implementation appear to use the exact same signature. Furthermore, this code compiled without issues in version 0.5.1.

### Reproduction Steps

The issue can be reproduced by attempting to compile the Mustela SSG project with V version 0.5.2.

- Clone the repository: git clone [https://github.com/filipos800/mustela](https://github.com/filipos800/mustela).
- Ensure you are using V version 0.5.2 (v --version).
- Run the build command: v .
- The compiler will fail with the interface implementation errors reported below.

> Note: This project compiles without any issues on V version 0.5.1.

### Expected Behavior

The code should compile successfully without errors, matching the behavior in V 0.5.1. If V 0.5.2 introduced stricter interface checking rules, the error message should clearly explain the type mismatch instead of showing identical types (expected fn (core.IEventData), not fn (core.IEventData)).

### Current Behavior

The compiler fails during compilation with the following error output:
```
src/app/app.v:47:23: error: `&app.App` incorrectly implements method `disconnect` of interface `src.core.IFree`: expected `fn (core.IEventData)`, not `fn (core.IEventData)` for parameter 3
   45 | pub fn (mut self App) module_free() {
   46 |     for mut mod in self.modules.reverse() {
   47 |         mod.module_free(mut self)
      |                       ~~~~
   48 |     }
   49 | }
Details: src.core.IFree has `fn disconnect(mut x core.IFree,   string,   string,   fn (core.IEventData))`
         src.app.App has `fn disconnect(mut self app.App, branch string, event string, handler fn (core.IEventData))`

src/app/app.v:53:23: error: `&app.App` incorrectly implements method `connect` of interface `src.core.IInit`: expected `fn (core.IEventData)`, not `fn (core.IEventData)` for parameter 3
   51 | fn (mut self App) module_init() {
   52 |     for mut mod in self.modules {
   53 |         mod.module_init(mut self)
      |                       ~~~~
   54 |     }
   55 | }
Details: src.core.IInit has `fn connect(mut x core.IInit,   string,   string,   fn (core.IEventData))`
         src.app.App has `fn connect(mut self app.App, branch string, event string, handler fn (core.IEventData))`
```
### Possible Solution

The bug seems to be a regression in V 0.5.2 related to interface method verification. Specifically, it appears that when checking if a struct method implements an interface method with a function pointer/closure parameter (like `fn (core.IEventData)`), the compiler incorrectly flags a mismatch even though the types are identical. 

Comparing the interface checking logic between V 0.5.1 and 0.5.2 might reveal where this strict/false-positive check was introduced.

### Additional Information/Context

* This is a clear regression, as the exact same codebase builds and runs successfully on V version **0.5.1**.
* Along with the two hard errors shown above, the compiler also outputs several notices and warnings about unused parameters/variables (e.g. `unused parameter: 'app'`, `unused variable: 'result_ptr'`), though those are likely just warnings and not the direct cause of the compilation failure.

### V version

0.5.2

### Environment details (OS name and version, etc.)

|V full version      |V 0.5.2 45ae01d23168b6372f734eeb38a77360bbcf184a.7647ce1
|:-------------------|:-------------------
|OS                  |linux, Debian GNU/Linux 13 (trixie) (VM)
|Processor           |4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
|Memory              |1.69GB/14.04GB
|                    |
|V executable        |/home/filip/.local/opt/v-052/v
|V last modified time|2026-07-12 22:51:55
|                    |
|V home dir          |OK, value: /home/filip/.local/opt/v-052
|VMODULES            |OK, value: /home/filip/.vmodules
|VTMP                |OK, value: /tmp/v_1000
|Current working dir |OK, value: /home/filip/Documents/code/mustela-engine
|                    |
|Git version         |git version 2.47.3
|V git status        |N/A
|.git/config present |false
|                    |
|cc version          |cc (Debian 14.2.0-19) 14.2.0
|gcc version         |gcc (Debian 14.2.0-19) 14.2.0
|clang version       |N/A
|tcc version         |tcc version 0.9.28rc 2025-02-13 HEAD@f8bd136d (x86_64 Linux)
|tcc git status      |N/A
|emcc version        |N/A
|glibc version       |ldd (Debian GLIBC 2.41-12+deb13u3) 2.41

**Comment by medvednikov** [comment]
The V3 compiler path for this interface/function-parameter case is fixed in #28056. V3 already accepted the implementation, but its C interface dispatcher emitted the internal `fn_ptr:...` encoding instead of the generated function-pointer typedef. The PR fixes all dispatcher declarations/definitions and adds a cross-module regression test.

This is a V3-only change; it does not change the compatibility-compiler behavior originally reported here.

**Comment by medvednikov** [comment]
This is fixed for V1 too in #28058. V1 now compares function-typed interface method parameters structurally across imported aliases, with a cross-module regression test. This complements the V3 fix in #28056.
