### ISSUE TITLE
The x.json2 decode example does not work with 0.3.3 d3870a0 

### ISSUE THREAD

**Issue by thomas-mangin** [vlang/v#17387]
### Describe the bug

copy and paste the decode code from https://modules.vlang.io/x.json2.html, it fails to compile

### Expected Behavior

It compiles and works

### Current Behavior

Compilation fails

```sh
❯ v run test_decode.v
test_decode.v:9:27: warning: unnecessary default value of `none`: struct fields are zeroed by default
    7 |     age      ?int = 20
    8 |     birthday time.Time
    9 |     deathday ?time.Time = none
      |                           ~~~~
   10 | }
   11 |
checker summary: 0 V errors, 1 V warnings, 0 V notices
/tmp/v_501/test_decode.10127853771688694456.tmp.c:3403:15: error: implicit declaration of function '_option_time__Time_str' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        string _t2 = _option_time__Time_str(it.deathday);
                     ^
/tmp/v_501/test_decode.10127853771688694456.tmp.c:3403:9: error: initializing 'string' (aka 'struct string') with an expression of incompatible type 'int'
        string _t2 = _option_time__Time_str(it.deathday);
               ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/thomas/Unix/v/vlib/strings/builder.c.v:90:3: warning: expression result unused [-Wunused-value]
 (*(int*)_t1.data);
  ^~~~~~~~~~~~~~~
/Users/thomas/Unix/v/vlib/io/io.v:15:3: warning: expression result unused [-Wunused-value]
 (*(int*)_t2.data);
  ^~~~~~~~~~~~~~~
  
...
  
/Users/thomas/Unix/v/vlib/x/json2/encoder.v:524:3: warning: expression result unused [-Wunused-value]
 (*(int*)_t25.data);
  ^~~~~~~~~~~~~~~~
/Users/thomas/Unix/v/vlib/x/json2/encoder.v:534:3: warning: expression result unused [-Wunused-value]
 (*(int*)_t27.data);
  ^~~~~~~~~~~~~~~~
50 warnings and 2 errors generated.
builder error:
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

### Reproduction Steps

```v
import x.json2
import time

struct Person {
mut:
    name     string
    age      ?int = 20
    birthday time.Time
    deathday ?time.Time = none
}

fn main() {
    resp := '{"name": "Bob", "age": 20, "birthday": ${time.now()}}'
    person := json2.decode[Person](resp)!
    /*
    struct Person {
      mut:
          name "Bob"
          age  20
          birthday "2022-03-11 13:54:25"
      }
    */
}
```

### Possible Solution

The recent option code change.

### V version

version: V 0.3.3 d3870a0

### Environment details (OS name and version, etc.)

OSX 13.1 (22C65) Ventura

**Comment by thomas-mangin** [comment]
The patch provided by @felipensp fixes the issue.
