### ISSUE TITLE
Error matching sum type of built-in types string | u32

### ISSUE THREAD

**Issue by ntrel** [vlang/v#5559]
**V version:** V 0.1.28 bbaf6e3
**OS:** Windows 8.

**What did you do?**
```v
type Version = string | u32

fn show(ver Version) {
	match ver {
		string {println(ver)}
		u32 {
			print('v')
			println(ver)
		}
	}
}

fn main() {
	mut v := Version(10)
	show(v)
	v = Version{'Jelly Bean'}
	show(v)
}
```

**What did you expect to see?**
Compile without errors.
 
**What did you see instead?**
```
V panic: get_type_symbol: invalid type (typ=0 idx=0). Compiler bug. This should
never happen
```

**Comment by ArtemkaKun** [comment]
Hi @ntrel ,
I can confirm that the error still exists for the fresh V (master branch from 20.01.2022). I did tests on Linux, but I believe it exists on Windows as well.

Can I ask you to change 2 things in this issue:
1. V changed a lot since the bug was reported, so I edited the code a bit to make it compile on the actual V version (2.4.0). You should edit the code in your issue and place the new one (see it below)
2. Error message also changed, so we should update it too (see it below)

Code
```v
type Version = string | u32

fn show(ver Version) {
	match ver {
		string {
			println(ver)
		}
		u32 {
			print('v')
			println(ver)
		}
	}
}

fn main() {
	mut v := Version(u32(10))
	show(v)
	v = Version('Jelly Bean')
	show(v)
}
```

Error
```
==================
/tmp/v_1000/v-bugs.13462249989732157216.tmp.c:11122: error: cannot convert 'unsigned int' to 'struct main__Version'
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

Thanks

**Comment by spytheman** [comment]
Commenting this: `println(ver)`, in the u32 match branch, fixes the compilation.

**Comment by yuyi98** [comment]
Fixed.

```v
type Version = string | u32

fn show(ver Version) {
	match ver {
		string {
			println(ver)
		}
		u32 {
			print('v')
			println(ver)
		}
	}
}

fn main() {
	mut v := Version(u32(10))
	show(v)
	v = Version('Jelly Bean')
	show(v)
}

PS D:\Test\v\tt1> v run .
v10
Jelly Bean
```
