### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by soumyakantiroychowdhury** [vlang/v#992]
**V version:** 
Downloaded using `git clone`

**OS:** 
CentOS 7.4
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

**What did you do?**

```
$ make
curl -Os https://raw.githubusercontent.com/vlang/vc/master/v.c
cc -std=gnu11 -w -o v v.c
v.c:372:3: error: expected specifier-qualifier-list before ‘_Atomic’
   _Atomic int fn_cnt;
   ^
v.c: In function ‘Fn_str’:
v.c:14100:21: error: unknown field ‘fn_cnt’ specified in initializer
                     .fn_cnt = 0,
                     ^
v.c:14101:21: error: unknown field ‘obfuscate’ specified in initializer
                     .obfuscate = 0};
                     ^
v.c: In function ‘new_table’:
v.c:14119:3: error: unknown field ‘obfuscate’ specified in initializer
   Table *t = ALLOC_INIT(Table, {
   ^
v.c:14119:3: error: unknown field ‘fn_cnt’ specified in initializer
v.c: In function ‘Table_cgen_name’:
v.c:14943:12: error: ‘Table’ has no member named ‘obfuscate’
   if (table->obfuscate && string_ne(f->name, tos2("main")) &&
            ^
v.c:14963:12: error: ‘Table’ has no member named ‘fn_cnt’
       table->fn_cnt++;
            ^
v.c:14964:24: error: ‘Table’ has no member named ‘fn_cnt’
       int tmp67 = table->fn_cnt;
                        ^
v.c:14968:18: error: ‘Table’ has no member named ‘fn_cnt’
       idx = table->fn_cnt;
                  ^
make: *** [v] Error 1


```

**What did you expect to see?**

 
**What did you see instead?**

**Comment by medvednikov** [comment]
You have a 7 year old C compiler. Update it please.

**Comment by soumyakantiroychowdhury** [comment]
Thanks @medvednikov. I was able to build with gcc 7.4.0 on Ubuntu 16.04. Could you please mention the minimum version of gcc / clang for future users to not encounter this issue?
