### PR TITLE
checker: ensure hex character literals don't overflow in strings

### LINKED ISSUE #10718: Character hex escape parsing overflow
**V version:** V 0.2.2 `47bf644`, timestamp: 2021-07-09 03:27:16 +0300
**OS:** Linux, Ubuntu 20.04.2 LTS

**What did you do?**

```
mut a := '\x1000000061'
println(a)
```

**What did you expect to see?**

An error message about characters literal overflow
 
**What did you see instead?**

The program prints `a` (hex code `61`) to the terminal

### PR DESCRIPTION
**Pull request by shadowninja55**
this pr ensures that long hex literals in strings like `'\xfffffffffff'` don't make it to the gen where they raise a c error. closes #10718.

### CODE REVIEW

File: vlib/v/checker/check_types.v [hunk 1]
```diff
@@ -487,6 +487,51 @@ pub fn (mut c Checker) string_inter_lit(mut node ast.StringInterLiteral) ast.Typ
 	return ast.string_type
 }
 
+fn is_hex_char(c byte) bool {
```
Comment (spaceface777) [inline vlib/v/checker/check_types.v:490]: Wouldn't the existing [byte.is_hex_digit](https://modules.vlang.io/#byte.is_hex_digit) method work?

Comment (shadowninja55) [reply vlib/v/checker/check_types.v:490]: > Wouldn't the existing [byte.is_hex_digit](https://modules.vlang.io/#byte.is_hex_digit) method work?

i wasn't aware of it, thanks.

**Review by spaceface777 — APPROVED** [review]

**Comment by medvednikov** [comment]
```
Run ./v -skip-unused -o v2 cmd/v && ./v2 -skip-unused -o v3 cmd/v && ./v3 -skip-unused -o v4 cmd/v
==================
/tmp/v/v2.17672942088380092196.tmp.c:53004: warning: implicit declaration of function 'string_at_with_check'
/tmp/v/v2.17672942088380092196.tmp.c:53004: error: '{' expected (got ";")
...
==================
(Use `v -cg` to print the entire error message)

```

**Comment by shadowninja55** [comment]
> ```
> Run ./v -skip-unused -o v2 cmd/v && ./v2 -skip-unused -o v3 cmd/v && ./v3 -skip-unused -o v4 cmd/v
> ==================
> /tmp/v/v2.17672942088380092196.tmp.c:53004: warning: implicit declaration of function 'string_at_with_check'
> /tmp/v/v2.17672942088380092196.tmp.c:53004: error: '{' expected (got ";")
> ...
> ==================
> (Use `v -cg` to print the entire error message)
> ```

yeah i saw that, i'm not sure what's causing it though.

**Comment by spytheman** [comment]
I think I fixed that failure in 9d241f7, it should be fine now.

**Comment by shadowninja55** [comment]
> I think I fixed that failure in [9d241f7](https://github.com/vlang/v/commit/9d241f75ebbd2de5fa95fe778a55c9bfa5c1fe4c), it should be fine now.

i'll try closing and reopening.
