### PR TITLE
checker: improve `fn` argument mismatch error

### PR DESCRIPTION
**Pull request by StunxFS**
This PR makes improvements to the changes introduced in the commit 7514783d8310925c7f60bad73e94bb37f7e9d4ac.

Before:
```v
main.v:4:12: error: expected 2 arguments, but got 3
        have (int literal, string, bool)
        want (int, string)

    2 | 
    3 | fn main() {
    4 |     x(1, "2", true)
      |               ~~~~
    5 | }
```

After:
```v
main.v:4:12: error: expected 2 arguments, but got 3
    2 | 
    3 | fn main() {
    4 |     x(1, "2", true)
      |               ~~~~
    5 | }
Details: have (int literal, string, bool)
         want (int, string)
```

### CODE REVIEW

**Review by Delta456 — APPROVED** [review]
I like this change. Great work!

**Review by spytheman — APPROVED** [review]
Excellent work.
