### ISSUE TITLE
`gen_vc` tool fails to compile

### ISSUE THREAD

**Issue by lberrymage** [vlang/v#6001]
**V version:**
```
$ ./v --version
V 0.1.28 fec9920
```
(latest `master` as of the time of writing)

**OS:**
Arch Linux, Zen kernel

**What did you do?**
```
$ git clone https://github.com/vlang/v
$ cd v
$ make
$ ./v cmd/tools/gen_vc.v
```

**What did you expect to see?**
No output - the result of a successful compilation
 
**What did you see instead?**
```
vlib/vweb/vweb.v:289:3: error: cannot assign string `string` as `net.http.Method` for field `method` 
  287 |         ws_func: 0
  288 |         user_ptr: 0
  289 |         method: vals[0]
      |         ~~~~~~~~~~~~~~~
  290 |         url: vals[1]
  291 |     }
vlib/vweb/vweb.v:308:16: error: the data type on the left of `in` (`net.http.Method`) does not match the array item type (`string`) 
  306 |     }
  307 |     //}
  308 |     if req.method in methods_with_form {
      |                   ~~
  309 |         app.vweb.parse_form(req.data)
  310 |     }
vlib/vweb/vweb.v:374:20: error: infix expr: cannot use `string` (right expression) as `net.http.Method` 
  372 |                 // For example URL `/register` matches route `/:user`, but `fn register()`
  373 |                 // should be called first.
  374 |                 if (req.method == 'GET' && url_words[0] == method.name && url_words.len == 1) || (req.method == 'POST' && url_words[0] + '_post' == method.name) {
      |                                ~~
  375 |                     println('easy match method=$method.name')
  376 |                     app.$method(vars)
vlib/vweb/vweb.v:383:20: error: infix expr: cannot use `string` (right expression) as `net.http.Method` 
  381 |                 // Get is default
  382 |                 if 'post' in attrs {
  383 |                     if req.method == 'POST' {
      |                                   ~~
  384 |                         route_words_a = attrs.filter(it.to_lower() != 'post').map(it[1..].split('/'))
  385 |                     }
vlib/vweb/vweb.v:387:20: error: infix expr: cannot use `string` (right expression) as `net.http.Method` 
  385 |                     }
  386 |                 } else if 'put' in attrs {
  387 |                     if req.method == 'PUT' {
      |                                   ~~
  388 |                         route_words_a = attrs.filter(it.to_lower() != 'put').map(it[1..].split('/'))
  389 |                     }
vlib/vweb/vweb.v:391:20: error: infix expr: cannot use `string` (right expression) as `net.http.Method` 
  389 |                     }
  390 |                 } else if 'patch' in attrs {
  391 |                     if req.method == 'PATCH' {
      |                                   ~~
  392 |                         route_words_a = attrs.filter(it.to_lower() != 'patch').map(it[1..].split('/'))
  393 |                     }
vlib/vweb/vweb.v:395:20: error: infix expr: cannot use `string` (right expression) as `net.http.Method` 
  393 |                     }
  394 |                 } else if 'delete' in attrs {
  395 |                     if req.method == 'DELETE' {
      |                                   ~~
  396 |                         route_words_a = attrs.filter(it.to_lower() != 'delete').map(it[1..].split('/'))
  397 |                     }
vlib/vweb/vweb.v:399:20: error: infix expr: cannot use `string` (right expression) as `net.http.Method` 
  397 |                     }
  398 |                 } else if 'head' in attrs {
  399 |                     if req.method == 'HEAD' {
      |                                   ~~
  400 |                         route_words_a = attrs.filter(it.to_lower() != 'head').map(it[1..].split('/'))
  401 |                     }
vlib/vweb/vweb.v:403:20: error: infix expr: cannot use `string` (right expression) as `net.http.Method` 
  401 |                     }
  402 |                 } else if 'options' in attrs {
  403 |                     if req.method == 'OPTIONS' {
      |                                   ~~
  404 |                         route_words_a = attrs.filter(it.to_lower() != 'options').map(it[1..].split('/'))
  405 |                     }
vlib/vweb/vweb.v:481:20: error: the data type on the left of `!in` (`net.http.Method`) does not match the array item type (`string`) 
  479 | 
  480 | fn (mut ctx Context) parse_form(s string) {
  481 |     if ctx.req.method !in methods_with_form {
      |                       ~~~
  482 |         return
  483 |     }
```

**Additional information**
I did a bisect and the offending commit appears to be fec9920b1a30e7c43c164d9f762510e1804dd282, the latest commit on `master` as of the time of writing. This makes sense based on the context of that commit.

**Comment by lberrymage** [comment]
I've got this mostly fixed now - just the one error on line 289 is left.

**Comment by medvednikov** [comment]
Fixed.
