### ISSUE TITLE
Invalid clobber register xmm0 error with tcc on OpenBSD

### ISSUE THREAD

**Issue by lcheylus** [vlang/v#22239]
### Describe the bug

With the new tcc compiler prebuilt for OpenBSD/amd64 (see https://github.com/vlang/tccbin/pull/55), I have some errors during tests with `thirdparty/mbedtls` library

### Reproduction Steps

- Clone V sources 
- Build on OpenBSD/amd64 with Clang v16.0.6
- Run essential tests with `tcc`: `VTEST_JUST_ESSENTIAL=1 ./v test-self`

### Expected Behavior

No error when executing self tests

### Current Behavior

Error with self tests:
- `vlib/net/http/http_test.v`
- `vlib/net/http/request_test.v`
- `vlib/net/http/server_test.v`

```bash
$ ./v -showcc -keepc test vlib/net/http/http_test.v
---- Testing... ----
 FAIL     0.000 ms vlib/net/http/http_test.v
>> compilation failed:
failed thirdparty object build cmd:
'/home/fox/dev/vlang.git/thirdparty/tcc/tcc.exe' -std=c99 -D_DEFAULT_SOURCE    -fPIC -I "/home/fox/dev/vlang.git/thirdparty/mbedtls/library" -I "/home/fox/dev/vlang.git/thirdparty/mbedtls/include" -I "/home/fox/dev/vlang.git/thirdparty/mbedtls/3rdparty/everest/include" -I "/home/fox/dev/vlang.git/thirdparty/mbedtls/3rdparty/everest/include/everest" -I "/home/fox/dev/vlang.git/thirdparty/mbedtls/3rdparty/everest/include/everest/kremlib" -o '/home/fox/.vmodules/cache/fe/feeb9b8e6784271d818c7f337407bce7.module.net.mbedtls.o' -c '/home/fox/dev/vlang.git/thirdparty/mbedtls/library/aesni.c'
builder error: /home/fox/dev/vlang.git/thirdparty/mbedtls/library/aesni.c:131: error: invalid clobber register 'xmm0'
```

**No error** with the same tests using Clang v16 or GCC v11 on OpenBSD/amd64
```bash
$ ./v -cc clang test vlib/net/http/http_test.v
---- Testing... ----
 OK      28.403 ms vlib/net/http/http_test.v
----
Summary for all V _test.v files: 1 passed, 1 total. Elapsed time: 17827 ms, on 1 job. Comptime: 17791 ms. Runtime: 28 ms.
```

**No error** with the same tests using tcc on Linux Debian/testing (amd64)
```bash
$ ./v test vlib/net/http/http_test.v
./v test vlib/net/http/http_test.v
---- Testing... ----
 OK       2.348 ms vlib/net/http/http_test.v
----
Summary for all V _test.v files: 1 passed, 1 total. Elapsed time: 1623 ms, on 1 job. Comptime: 1619 ms. Runtime: 2 ms.
```

### Additional Information/Context

There is an old issue related to the same error (`invalid clobber register 'xmm0'` error) on FreeBSD 13.1 => issue #16727

### V version

V 0.4.7 5f495e2

### Environment details (OS name and version, etc.)

V full version: V 0.4.7 acf6b34.5f495e2
OS: openbsd, 7.6, GENERIC.MP#312
Processor: 2 cpus, 64bit, little endian

getwd: /home/fox/dev/vlang.git
vexe: /home/fox/dev/vlang.git/v
vexe mtime: 2024-09-17 07:14:24

vroot: OK, value: /home/fox/dev/vlang.git
VMODULES: OK, value: /home/fox/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.46.0
Git vroot status: weekly.2024.37-11-g5f495e23
.git/config present: true

CC version: OpenBSD clang version 16.0.6
thirdparty/tcc status: thirdparty-openbsd-amd64 8205cc59
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.
