### ISSUE TITLE
checker: regression with aliased function wrapped in Option type after PR #27960

### ISSUE THREAD

**Issue by skandhas** [vlang/v#27965]
### Describe the bug

The V type checker triggers an unexpected compilation error when a struct implements an interface method that returns an aliased function wrapped in an Option type (`?MathOp`). 

This seems to be an unhandled edge case or regression following the changes introduced in PR #27960 (where standard alias resolution was fixed but nested Option types were missed).

### Reproduction Steps

```v
type MathOp = fn (int, int) int

interface Calculator {
	get_operation() ?MathOp
}

struct SimpleCalc {}

// Both interface and struct implementation use exactly the same `MathOp` alias
fn (s SimpleCalc) get_operation() ?MathOp {
	return fn (a int, b int) int {
		return a + b
	}
}

fn main() {
	// This line triggers the unexpected compiler error
	calc := Calculator(SimpleCalc{})
	_ = calc
}
```

### Expected Behavior

The code should compile successfully since both the interface and the struct method share the exact same ?MathOp return type.

### Current Behavior

```
main.v:18:10: error: `SimpleCalc` incorrectly implements method `get_operation` of interface `Calculator`: expected return type `?fn (int, int) int`
   16 | fn main() {
   17 |     // This line triggers the unexpected compiler error
   18 |     calc := Calculator(SimpleCalc{})
      |             ~~~~~~~~~~~~~~~~~~~~~~~~
   19 |     _ = calc
   20 | }
Details: main.Calculator has `fn get_operation(x main.Calculator) ?fn (int, int) int`
         main.SimpleCalc has `fn get_operation(s main.SimpleCalc) ?fn (int, int) int`
main.v:18:10: error: `SimpleCalc` does not implement interface `Calculator`, cannot cast `SimpleCalc` to interface `Calculator`
   16 | fn main() {
   17 |     // This line triggers the unexpected compiler error
   18 |     calc := Calculator(SimpleCalc{})
      |             ~~~~~~~~~~~~~~~~~~~~~~~~
   19 |     _ = calc
   20 | }
```

### V version

V 0.5.2 dff6356

### Environment details (OS name and version, etc.)

```
|V full version      |V 0.5.2 09062b4577f57aa3ca57adb528d751824d8f51a8.dff6356
|:-------------------|:-------------------
|OS                  |windows, Microsoft Windows 11 Home 26200 64-bit
|Processor           |16 cpus, 64bit, little endian, 12th Gen Intel(R) Core(TM) i5-1240P
|Memory              |18.41GB/31.58GB
|                    |
|V executable        |D:\sdks\v\v.exe
|V last modified time|2026-07-28 11:17:58
|                    |
|V home dir          |OK, value: D:\sdks\v
|VMODULES            |OK, value: C:\Users\skand\.vmodules
|VTMP                |OK, value: C:\Users\skand\AppData\Local\Temp\v_0
|Current working dir |OK, value: D:\workd\vtools\bug\2
|                    |
|Git version         |git version 2.51.1
|V git status        |dff6356b
|.git/config present |true
|                    |
|cc version          |cc (Rev3, Built by MSYS2 project) 16.1.0
|gcc version         |gcc (Rev3, Built by MSYS2 project) 16.1.0
|clang version       |clang version 22.1.7 (https://github.com/msys2/MINGW-packages b8f306ad57e0c8f3f15aed0dc809d7e3e8e2eee9)
|msvc version        |N/A
|tcc version         |tcc version 0.9.28rc 2026-07-14_HEAD@d9d02c56* (x86_64 Windows)
|tcc git status      |thirdparty-windows-amd64 f7c7199b-dirty
|emcc version        |N/A
|glibc version       |ldd (cygwin) 3.6.9
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.
