### ISSUE TITLE
enforcing private module.init() breaks constructor methods

### ISSUE THREAD

**Issue by lobotony** [vlang/v#2309]
**V version:** V 0.1.21 336e82d
**OS:** MacOS 10.15

**What did you do?**

in ./bitmap/bitmap.v

	module bitmap

	struct Bitmap {
	pub:
		width int
		height int
	}

	pub fn (self mut Bitmap) init(w int, h int) Bitmap {
		return Bitmap{w, h}
	}

in ./main.v

	import bitmap

	fn main() {
		mut b := Bitmap{}
		b.init(13, 14)
		println(b)
	}

**What did you expect to see?**
successful compilation and output of struct.str()
 
**What did you see instead?**
compilation error: init function cannot be public

I strongly believe that even if the compiler would enforce private module.init() functions, these should be handled unrelated from init methods defined on structs. 

I stumbled over this because I used Swift-like init / deinit pairs of functions for the lifecycle of my objects. I can switch to something else of course, maybe construct / deconstruct? But it still seems like an unnecessarily harsh restriction.

Also, module inits in for example python are named distinctly differently. Maybe the module init should have been called module_init() instead of prohibiting the use of init() for everything else in the module?

Please consider changing this.

**Comment by avitkauskas** [comment]
@lobotony, your code looks a bit strange for me:
- your `struct Bitmap` fields are immutable, but you try to change them
- you return a new `struct Bitmap` from `init(...)`, not changing the receiver.
If you change the code like below, it works with V 0.1.21 c7e47e6:
`bitmap/bitmap.v`
```v
module bitmap

struct Bitmap {
pub mut:
	width int
	height int
}

pub fn (b mut Bitmap) init(w int, h int) {
    b.width = w
    b.height = h
}
```
`main.v`
```v
import bitmap

fn main() {
	mut b := bitmap.Bitmap{}
	b.init(13, 14)
	println(b)
}
```
`v build module bitmap`
`v run main.v`
Result:
```
{
	width: 13
	height: 14
}
```

**Comment by lobotony** [comment]
thanks @avitkauskas , you were right, my code was weird. Haven't been in great shape this week, and it shows in my bug reports. 
But ... your code still doesn't compile here. Using V 0.1.21 81f8b26, I'm still getting the same error:
bitmap.v:9:27: init function cannot be public

**Comment by avitkauskas** [comment]
Yes, @lobotony. You are right, with the last changes it does not compile.
And I think that `init()` functions defined with the receivers (as structure methods) should be allowed:
```v
pub fn (s Struct) init() {...} // should be allowed
```
and only module init functions should not be allowed
```v
fn init() {...} // should be private module init function
```

**Comment by medvednikov** [comment]
`pub fn (s Struct) init() {...}` is allowed.

**Comment by medvednikov** [comment]
Oh, but it can't be public :)

Will fix.

**Comment by medvednikov** [comment]
Fixed.
