### ISSUE TITLE
C compilation error: cannot convert 'struct v__ast__Expr' to 'struct v__ast__Expr *'

### ISSUE THREAD

**Issue by fermarsan** [vlang/v#23387]
### Describe the bug

Trying to compile the source code of the [**Aixt** project](https://github.com/fermarsan/aixt) this issue appears:

================== C compilation error (from tcc): ==============
cc: /tmp/v_1000/aixt.01JGWDYWCSRVQBPKK7JYWE2KME.tmp.c:77817: error: cannot convert 'struct v__ast__Expr' to 'struct v__ast__Expr *'
=================================================================

The source code of **Aixt** compiles with V 0.4.8 but fails with 0.4.9.

### Reproduction Steps

I am not sure in which specific part of the source code the issue is presented, so I provide the complete repository:  
https://github.com/fermarsan/aixt.git

### Expected Behavior

To compile the source code of **Aixt** without errors.

### Current Behavior

The compilation process fails.

### Possible Solution

I think the issue is related with the implementation of **sum types** in C as pointers to structs. Any change related in the version 0.4.9?

### Additional Information/Context

Context: **Aixt** project uses the modules `v.ast`, `v.token`, `v.pref`, `v.parser` and `v.checker` to transpile a subset of Vlang for microcontrollers, generation a custom C code generation.

### V version

0.4.9

### Environment details (OS name and version, etc.)

Linux Mint Debian Edition 6
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by fermarsan** [comment]
Nice.....    thanks a lot
