### ISSUE TITLE
vlib OS error: undefined ident: autofree

### ISSUE THREAD

**Issue by joysahimar** [vlang/v#21304]
### Describe the bug

i'm using `import os` in my project, but getting error: undefined ident: `autofree`

### Reproduction Steps

Simple Code:
```v
import os

fn main() {
	println(os.environ())
}
```

### Expected Behavior

No Error

### Current Behavior

```bash
/home/joycomp/vlang/v/vlib/os/os.c.v:542:8: error: undefined ident: `autofree`
  540 |         str := unsafe { tos(&u8(buf), if nr_chars < 0 { 0 } else { nr_chars }) }
  541 |         ret := str.clone()
  542 |         $if !autofree {
      |              ~~~~~~~~
  543 |             unsafe {
  544 |                 if nr_chars > 0 && buf != 0 {
/home/joycomp/vlang/v/vlib/os/os.c.v:542:7: error: unknown var: `autofree`
  540 |         str := unsafe { tos(&u8(buf), if nr_chars < 0 { 0 } else { nr_chars }) }
  541 |         ret := str.clone()
  542 |         $if !autofree {
      |             ^
  543 |             unsafe {
  544 |                 if nr_chars > 0 && buf != 0 {
If the code of your project is in multiple files, try with `v .` instead of `v test.v`
```

### V version

V 0.4.5 e6b43a1

### Environment details (OS name and version, etc.)

Same error when `v doctor`
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by JalonSolov** [comment]
Looks like you just need to update your V.  This example works with `V 0.4.5 0f5da89`

**Comment by joysahimar** [comment]
I tried `v up` still the same error. maybe I'll try `clone` and `make` again. thanks.
