### ISSUE TITLE
generic struct initalisation regression after 90591eb81

### ISSUE THREAD

**Issue by spytheman** [vlang/v#17824]
### Describe the bug

```
/v/misc/bugs/t.v:17:12: error: generic struct init must specify type parameter, e.g. Foo[T]
   15 | 
   16 | pub fn (t Transform[T]) clone() Transform[T] {
   17 |     return Transform[T]{
      |            ~~~~~~~~~~~~~
   18 |         ...t
   19 |     }
```

### Expected Behavior

The program should compile and run cleanly.

### Current Behavior

It triggers a checker error.

### Reproduction Steps

```v
module main

pub struct Time[T] {
pub mut:
    start T
    end   T
}

pub struct Transform[T] {
pub mut:
    time   Time[T]
    before []T
    after  []T
}

pub fn (t Transform[T]) clone() Transform[T] {
    return Transform[T]{
        ...t
    }
}

fn main() {
    a := Transform[f64]{
        before: [0.0, 0.0]
        after: [320.0, 240.0]
    }

    b := a.clone()

    println(b)
}
```

### Possible Solution

The checker error should be more specific, so that it does not trigger for this case.
If I comment out `vlib/v/checker/struct.v:300`, then that program compiles and runs.

### V version

V 0.3.3 4ef6e16

### Environment details (OS name and version, etc.)

Ubuntu 20.04 LTS

**Comment by spytheman** [comment]
A bisection of the v repo, shows that it regressed after 90591eb81 :
![image](https://user-images.githubusercontent.com/26967/228809975-3cca4a4e-4b0b-4f4e-80c5-ade3b2ca2b31.png)
