### ISSUE TITLE
autofree c compilation error with array.map and anonymous function

### ISSUE THREAD

**Issue by lilenvy** [vlang/v#7599]
**V version:** V 0.2 70c1364.1383771
**OS:** Ubuntu 20.10

**What did you do?**
`v -autofree run main.v`

```v
fn main() {
	y := '1 2'.split(' ').map(fn (v string) string {
		return v
	})
	println(y)
}
```

**What did you expect to see?**
`['1', '2']`
 
**What did you see instead?**
C error:
```
 v -autofree -cg run autofree_split.v 
Compilation with tcc failed. Retrying with cc ...
/tmp/v/autofree_split.11866346441538416124.tmp.c: In function ‘anon_75_18_18’:
/tmp/v/autofree_split.11866346441538416124.tmp.c:1377:17: error: ‘it’ undeclared (first use in this function); did you mean ‘i8’?
 1377 |    string_free(&it); // autofreed var main false
      |                 ^~
      |                 i8
/tmp/v/autofree_split.11866346441538416124.tmp.c:1377:17: note: each undeclared identifier is reported only once for each function it appears in
/tmp/v/autofree_split.11866346441538416124.tmp.c:1380:16: error: ‘y’ undeclared (first use in this function)
 1380 |    array_free(&y); // autofreed var main false
      |                ^
builder error: 
==================
```

**Comment by lilenvy** [comment]
**What about shorthand with `it`?**
it works!
```v
fn main() {
	y := '1 2'.split(' ').map(it)
	println(y)
}
```

**What about non-anon function?**
Also works
```v
fn main() {
	y := '1 2'.split(' ').map(do_nothing)
	println(y)
}

fn do_nothing(s string) string {
	return s
}
```
yes it works with a declared `fn` or with a fn variable
```v
fn main() {
	do_nothing := fn (s string) string {
		return s
	}
	y := '1 2'.split(' ').map(do_nothing)
	println(y)
}
```

**Comment by ArtemkaKun** [comment]
Hi @lilenvy ,

original code from the issue works on a fresh V (0.2.4) and returns an expected output
