### ISSUE TITLE
C compiler error with arrays.filter_indexed

### ISSUE THREAD

**Issue by 7underlines** [vlang/v#26959]
### Describe the bug

Running `./v -g -o vdbg cmd/v && ./vdbg '1.v' && '1'` on `1.v` produced a compiler error.

### Reproduction Steps

```sh
./v -g -o vdbg cmd/v && ./vdbg '1.v' && '1'
```

```v
import arrays

struct Product {
	mut:
	cross_sell_skus []string
}

fn main() {
	mut products := []Product{}
	for mut product in products {
		product.cross_sell_skus = arrays.filter_indexed[string](product.cross_sell_skus, fn [products, product] (_ int, css string) bool {
			println(product)
			println(products)
			return true
		})
	}
}
```

### Expected Behavior

This code compiles on V 0.4.12, but doesn't on V 0.5.1 :(

### Current Behavior

```
================== C compilation error (from cc): ==============
cc: /tmp/v_502/1.01KPX9XHSY5ERFCAMKMT4J630K.tmp.c:2710:37: error: indirection requires pointer operand ('main__Product' (aka 'struct main__Product') invalid)
cc:  2710 |         builtin__println(main__Product_str(*_V_closure_ctx->product));
cc:       |                                            ^~~~~~~~~~~~~~~~~~~~~~~~
cc: 1 error generated.
================================================================
Try passing `-g` when compiling, to see a .v file:line information, that correlates more with the C error.
(Alternatively, pass `-show-c-output`, to print the full C error message).
builder error: 
==================
C error found while compiling generated C code.
This can be caused by invalid C interop code, C compiler flags, or a V compiler bug.
If your code is pure V and this still happens, please report it using `v bug file.v`,
or goto https://github.com/vlang/v/issues/new/choose .
You can also use #help on Discord: https://discord.gg/vlang .
```

### Additional Information/Context

Generated by `v bug` from `1.v`.

### V version

V 0.5.1 574ab6f

### Environment details (OS name and version, etc.)

```
|V full version      |V 0.5.1 8986645ee93015bf9b44e7839c3a3370aff4f51b.574ab6f
|:-------------------|:-------------------
|OS                  |macos, macOS, 26.3.1, 25D771280a
|Processor           |12 cpus, 64bit, little endian, Apple M4 Pro
|Memory              |15.61GB/48GB
|                    |
|V executable        |/Users/7underlines/a/v/v
|V last modified time|2026-04-23 12:28:43
|                    |
|V home dir          |OK, value: /Users/7underlines/a/v
|VMODULES            |OK, value: /Users/7underlines/.vmodules
|VTMP                |OK, value: /tmp/v_502
|Current working dir |OK, value: /Users/7underlines/a/falle_sw6_import
|                    |
|Git version         |git version 2.50.1 (Apple Git-155)
|V git status        |0.5.1-1226-g574ab6f4
|.git/config present |true
|                    |
|cc version          |Apple clang version 21.0.0 (clang-2100.0.123.102)
|gcc version         |Apple clang version 21.0.0 (clang-2100.0.123.102)
|clang version       |Apple clang version 21.0.0 (clang-2100.0.123.102)
|tcc version         |tcc version 0.9.28rc 2026-01-10 HEAD@5ec0e6f8 (AArch64 Darwin)
|tcc git status      |thirdparty-macos-arm64 f995efa3
|emcc version        |N/A
|glibc version       |N/A
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by 7underlines** [comment]
Thank you for the fast fix! ⭐️
