### ISSUE TITLE
C compilation error on `a.map(it.map(it + 2))`

### ISSUE THREAD

**Issue by spytheman** [vlang/v#6132]
**V version:** V 0.1.29 b2fee21
**OS:** Ubuntu 16.04

**What did you do?**
I tried to run this program:
```v
    a := [ [1,2,3], [4,5,6], [7,8,9] ]
    x := a.map(it.map(it + 2))
    eprintln('a: $a')
    eprintln('x: $x')
```

**What did you expect to see?**
```
a: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
x: [[3, 4, 5], [6, 7, 8], [9, 10, 11]]
```
 
**What did you see instead?**
```
==================
                          ^
/dev/shm/v/a.tmp.c:9484:18: error: use of undeclared identifier 'it'
        int _t191_len = it.len;
                        ^
/dev/shm/v/a.tmp.c:9487:22: error: member reference base type 'int' is not a structure or union
                int it = ((int*) it.data)[_t192];
                                 ~~^~~~~
....
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.
```

**Comment by spytheman** [comment]
NB: a variation of this works as it should:

```v
a := [ [1,2,3], [4,5,6], [7,8,9] ]
x := a.map(fn (x []int) []int { return x.map(it + 2)})
eprintln('a: $a')
eprintln('x: $x')
```

**Comment by spytheman** [comment]
Closing, because it works in latest V 0.2.1 bb4ac0a .
