### ISSUE TITLE
C error using `rune_bytes` as variable name

### ISSUE THREAD

**Issue by jorgeluismireles** [vlang/v#25063]
<details>
<summary>V version: V 0.4.11 8a7949d, press to see full `v doctor` output</summary>

|V full version      |V 0.4.11 7dc3889f19e7bdc6fb803ad4d1d65fd9d50c6e0c.8a7949d
|:-------------------|:-------------------
|OS                  |linux, Ubuntu 22.04.5 LTS
|Processor           |4 cpus, 64bit, little endian, Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz
|Memory              |0.53GB/3.7GB
|                    |
|V executable        |/home/jorge/v/v
|V last modified time|2025-08-07 16:58:05
|                    |
|V home dir          |OK, value: /home/jorge/v
|VMODULES            |OK, value: /home/jorge/.vmodules
|VTMP                |OK, value: /tmp/v_1000
|Current working dir |OK, value: /home/jorge/bugs
|                    |
|Git version         |git version 2.34.1
|V git status        |weekly.2025.16-576-g8a7949d9
|.git/config present |true
|                    |
|cc version          |cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
|gcc version         |gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
|clang version       |Ubuntu clang version 14.0.0-1ubuntu1.1
|tcc version         |tcc version 0.9.28rc 2025-02-13 HEAD@f8bd136d (x86_64 Linux)
|tcc git status      |thirdparty-linux-amd64 696c1d84
|emcc version        |emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.5 ()
|glibc version       |ldd (Ubuntu GLIBC 2.35-0ubuntu3.10) 2.35

</details>

**What did you do?**
`./v -g -o vdbg cmd/v && ./vdbg  250807.v && 250807`
```v
fn main() {
	mut r := rune(0)
	rune_bytes := r.bytes()
	_ = rune_bytes
}

```

**What did you see?**
```
================== C compilation error (from tcc): ==============
cc: /tmp/v_1000/250807.01K22QJEFY9KRGE9JN1S37WR90.tmp.c:1538: error: function pointer expected
=================================================================
(You can pass `-cg`, or `-show-c-output` as well, to print all the C error messages).
builder error: 
==================
C error found. It should never happen, when compiling pure V code.
This is a V compiler bug, please report it using `v bug file.v`,
or goto https://github.com/vlang/v/issues/new/choose .
You can also use #help on Discord: https://discord.gg/vlang .
```

**What did you expect to see?**

Accept variable name `rune_bytes`

**Workaround**

Don't use `rune_bytes`, but well...

**Comment by spytheman** [comment]
Unfortunately, I've reverted the PR that fixed it, for performance reasons.

It is still a problem, but I think we need a faster solution, that does not need to second guess the method encoding scheme (for example, by making all builtin methods use a `builtin__` prefix, just like what the other modules use, with potentially a way to opt out) etc.

**Comment by dy-tea** [comment]
This should be fixed now, try this on latest V.

**Comment by jorgeluismireles** [comment]
> This should be fixed now, try this on latest V.

Yes, works with V 0.4.11 d73ebc
