### ISSUE TITLE
C error on using `in` operator in a loop header

### ISSUE THREAD

**Issue by zeddidragon** [vlang/v#3003]
**V version:** `❯ v --version
V 0.1.23 0fb0c43`
**OS:** macOS High Sierra 10.13.6

**What did you do?**
```v
fn main() {
  mut m := map[string]string
  m['a'] = 'b'
  m['b'] = 'c'

  for n := 'a'; n in m; n = m[n] {
    print(n)
  }
}
```

**What did you expect to see?**
`abc`
 
**What did you see instead?**
```
❯ v run test.v -g
C compiler=cc
all .v files:
["/Users/zeddy/bin/v_macos/vlib/builtin/array.v", "/Users/zeddy/bin/v_macos/vlib/builtin/builtin.v", "/Users/zeddy/bin/v_macos/vlib/builtin/builtin_nix.v", "/Users/zeddy/bin/v_macos/vlib/builtin/cfns.v", "/Users/zeddy/bin/v_macos/vlib/builtin/float.v", "/Users/zeddy/bin/v_macos/vlib/builtin/hashmap.v", "/Users/zeddy/bin/v_macos/vlib/builtin/int.v", "/Users/zeddy/bin/v_macos/vlib/builtin/map.v", "/Users/zeddy/bin/v_macos/vlib/builtin/option.v", "/Users/zeddy/bin/v_macos/vlib/builtin/string.v", "/Users/zeddy/bin/v_macos/vlib/builtin/utf8.v", "/Users/zeddy/bin/v_macos/vlib/builtin/utf8_util.v", "/Users/zeddy/bin/v_macos/vlib/strings/builder_c.v", "/Users/zeddy/bin/v_macos/vlib/strings/similarity.v", "/Users/zeddy/bin/v_macos/vlib/strings/strings.v", "/Users/zeddy/bin/v_macos/vlib/strconv/atoi.v", "test.v"]
/Users/zeddy/git/advent2019/test.v:6:26: error: unexpected type name 'bool': expected expression
 string tmp1 = tos3(""); bool tmp2 = map_get(/*test.v : 5*/ m , n, & tmp1);
                         ^
/Users/zeddy/git/advent2019/test.v:8:2: error: expected expression
 if (!tmp2) tmp1 = tos((byte *)"", 0);
 ^
/Users/zeddy/git/advent2019/test.v:8:2: error: expected ')'
/Users/zeddy/git/advent2019/test.v:5:6: note: to match this '('
 for (
     ^
/Users/zeddy/git/advent2019/test.v:5:57: error: use of undeclared identifier 'tmp1'
string n= tos3("a")  ; (_IN_MAP( ( n ),  m ))  ;  n  =  tmp1 ) {
                                                        ^
4 errors generated.
V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
```

It looks like the compiler needs to declare `tmp2` before the function header?

The following rewrite compiles and gives the expected result:
```v
fn main() {
  mut m := map[string]string
  m['a'] = 'b'
  m['b'] = 'c'

  mut n := 'a'
  for {
    print(n)
    if !(n in m) { break }
    n = m[n]
  }
  print(n)
}
```

**Comment by ka-weihe** [comment]
Works in V 0.1.26 50a8373. 
Expected result should be:
```
ab
```
Not ->
```
abc
```
