### ISSUE TITLE
Give better error information when `If` assignment without `else` 

### ISSUE THREAD

**Issue by dhonx** [vlang/v#3420]
**V version:** V 0.1.24 3425934
**OS:** Linux

**What did you do?**
```v
struct Person {
mut:
    name string = 'Person'
    age int = 8
}

fn new_person(name string, age int) Person {
    mut _person := Person{}
    _person.name = if name != '' { name }
    return _person
}

fn main() {
    don := new_person('', 20)
    println(don.name)
}
```

**What did you expect to see?**
Better error information. E.g `The If assignment requires else` or something better than that.
**OR**
If we allow that, then if the `if` fails, the `_person.name` will remain with the default value which is `'Person'`.
 
**What did you see instead?**
```
main.tmp.c: In function 'main__new_person':
main.tmp.c:3876:62: error: expected ')' before ';' token
  _person .name  =  ((string_ne( name , tos3("") ) ) ? ...
(Use `v -g` to print the entire error message)

V error: C error. This should never happen. 
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
```

**Comment by Delta456** [comment]
I think we will need `else` case as it will make sense to have it.

**Comment by lutherwenxu** [comment]
I think it would be better for it to be an optional if `else` is not provided.
Just to make the definition of the `if` statement self-contained instead of making its syntax rely on whether its value is used.

**Comment by cliserkad** [comment]
Is the use of if/else as a sort of lambda for variables necessary? The example could be written as
```
fn new_person(name string, age int) Person {
    mut _person := Person{}
    if(name != '')
        _person.name = name
    return _person
}
```
Wondering how to use the special syntax efficiently.

**Comment by Ivo-Balbaert** [comment]
This code now gives a proper V error message:

json_primitives.v:9:19: error: `if` expression needs `else` clause 
    7 | fn new_person(name string, age int) Person {
    8 |     mut person := Person{}
    9 |     person.name = if name != '' { name }
      |                   ~~
   10 |     return person
   11 | }

If indeed this remains true, this issue can be closed I think.

**Comment by bombsimon** [comment]
I still thing this is an issue and should be re-opened. Haven't dug into the details but I noticed this test working in  `V 0.1.23` is no longer working in `V 0.1.29 99dd72e`.

```sh
$ tail -20 *.v
==> example.v <==
module example

pub fn x() []int {
	return [1, 2, 3]
}

==> example_test.v <==
module example

fn test_x() {
	assert array_eq(x(), [1, 2, 3])
	if !array_eq(x(), [1, 2, 3]) {
		println('x was not 1')
	}
}

fn array_eq(a, b []int) bool {
	if a.len != b.len {
		return false
	}
	for i, v in a {
		if v != b[i] {
			return false
		}
	}
	return true
}
```

```sh
$ v test example_test.v
----------------------------------- Testing... ---------------------------------
FAIL    55.918 ms example_test.v
example_test.v:5:2: error: `if` expression needs `else` clause
    3 | fn test_x() {
    4 |     assert array_eq(x(), [1, 2, 3])
    5 |     if !array_eq(x(), [1, 2, 3]) {
      |     ~~
    6 |         println('x was not 1')
    7 |     }


--------------------------------------------------------------------------------
       56.370 ms <=== total time spent running V _test.v files
                 ok, fail, skip, total =     0, [31m    1[39m,     0,     1
```

**Comment by medvednikov** [comment]
But I don't see an if expression here?

**Comment by bombsimon** [comment]
I'ts right there, where to error points to: `example_test.v:5:2:`. This does not yield an error:

```v
fn test_x() {
	assert array_eq(x(), [1, 2, 3])
	if !array_eq(x(), [1, 2, 3]) {
		println('x was not 1')
	} else {
		println('No error will be printed now')
 	}
}
```

**Comment by medvednikov** [comment]
It's not an if expression, it's a simple if statement.

**Comment by medvednikov** [comment]
But I see that the compiler mistakenly thinks it's an expression. Can be solved by adding a random statement:

```
 assert array_eq(x(), [1, 2, 3])
 println(1)
```

Good find. This should be a separate issue.

**Comment by bombsimon** [comment]
My bad, I mixed up expression and statement. I added #6233, thanks!
