### PR TITLE
checker: fix option-wrapped function alias returns

### LINKED ISSUE #27965: checker: regression with aliased function wrapped in Option type after PR #27960
### Describe the bug

The V type checker triggers an unexpected compilation error when a struct implements an interface method that returns an aliased function wrapped in an Option type (`?MathOp`). 

This seems to be an unhandled edge case or regression following the changes introduced in PR #27960 (where standard alias resolution was fixed but nested Option types were missed).

### Reproduction Steps

```v
type MathOp = fn (int, int) int

interface Calculator {
	get_operation() ?MathOp
}

struct SimpleCalc {}

// Both interface and struct implementation use exactly the same `MathOp` alias
fn (s SimpleCalc) get_operation() ?MathOp {
	return fn (a int, b int) int {
		return a + b
	}
}

fn main() {
	// This line triggers the unexpected compiler error
	calc := Calculator(SimpleCalc{})
	_ = calc
}
```

### Expected Behavior

The code should compile successfully since both the interface and the struct method share the exact same ?MathOp return type.

### Current Behavior

```
main.v:18:10: error: `SimpleCalc` incorrectly implements method `get_operation` of interface `Calculator`: expected return type `?fn (int, int) int`
   16 | fn main() {
   17 |     // This line triggers the unexpected compiler error
   18 |     calc := Calculator(SimpleCalc{})
      |             ~~~~~~~~~~~~~~~~~~~~~~~~
   19 |     _ = calc
   20 | }
Details: main.Calculator has `fn get_operation(x main.Calculator) ?fn (int, int) int`
         main.SimpleCalc has `fn get_operation(s main.SimpleCalc) ?fn (int, int) int`
main.v:18:10: error: `SimpleCalc` does not implement interface `Calculator`, cannot cast `SimpleCalc` to interface `Calculator`
   16 | fn main() {
   17 |     // This line triggers the unexpected compiler error
   18 |     calc := Calculator(SimpleCalc{})
      |             ~~~~~~~~~~~~~~~~~~~~~~~~
   19 |     _ = calc
   20 | }
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### V version

V 0.5.2 dff6356

### Environment details (OS name and version, etc.)

```
|V full version      |V 0.5.2 09062b4577f57aa3ca57adb528d751824d8f51a8.dff6356
|:-------------------|:-------------------
|OS                  |windows, Microsoft Windows 11 Home 26200 64-bit
|Processor           |16 cpus, 64bit, little endian, 12th Gen Intel(R) Core(TM) i5-1240P
|Memory              |18.41GB/31.58GB
|                    |
|V executable        |D:\sdks\v\v.exe
|V last modified time|2026-07-28 11:17:58
|                    |
|V home dir          |OK, value: D:\sdks\v
|VMODULES            |OK, value: C:\Users\skand\.vmodules
|VTMP                |OK, value: C:\Users\skand\AppData\Local\Temp\v_0
|Current working dir |OK, value: D:\workd\vtools\bug\2
|                    |
|Git version         |git version 2.51.1
|V git status        |dff6356b
|.git/config present |true
|                    |
|cc version          |cc (Rev3, Built by MSYS2 project) 16.1.0
|gcc version         |gcc (Rev3, Built by MSYS2 project) 16.1.0
|clang version       |clang version 22.1.7 (https://github.com/msys2/MINGW-packages b8f306ad57e0c8f3f15aed0dc809d7e3e8e2eee9)
|msvc version        |N/A
|tcc version         |tcc version 0.9.28rc 2026-07-14_HEAD@d9d02c56* (x86_64 Windows)
|tcc git status      |thirdparty-windows-amd64 f7c7199b-dirty
|emcc version        |N/A
|glibc version       |ldd (cygwin) 3.6.9
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

### PR DESCRIPTION
**Pull request by medvednikov**
## Summary
- compare separately materialized function alias return types under matching Option/Result wrappers
- keep wrapped compatibility limited to identical function signatures so V1 C wrapper structs stay ABI-compatible
- cover V3 wrapped-return matching and preserve function-literal payloads in valid optional alias returns

## Tests
- `./vnew vlib/v/tests/interfaces/interface_method_fn_type_alias_return_test.v`
- `./vnew -silent test vlib/v/tests/interfaces/`
- `./vnew -silent test vlib/v/checker/`
- `./vnew -silent vlib/v/compiler_errors_test.v`
- `./vnew vlib/v3/tests/interface_return_alias_compatibility_test.v`
- `./vnew -silent test vlib/v3/transform/`
- generated V3 C compiled with Clang using `-Werror=incompatible-function-pointer-types` and ran successfully
- `./vnew -silent test vlib/v/` (stopped at 1735/2342; two pre-existing environment-sensitive failures observed)

Fixes #27965

### CODE REVIEW

File: vlib/v/ast/table.v [hunk 1]
```diff
@@ -506,20 +506,28 @@ fn (t &Table) fn_type_components_are_compatible(left_type Type, right_type Type,
...
+		return false
+	}
+	if (unaliased_left.has_option_or_result() || unaliased_right.has_option_or_result())
+		&& unaliased_left.flags() != unaliased_right.flags() {
+		return false
+	}
+	left_sym := t.sym(unaliased_left)
+	right_sym := t.sym(unaliased_right)
+	if left_sym.info is FnType && right_sym.info is FnType {
+		return t.fn_types_are_compatible(left_sym.info.func, right_sym.info.func, 0)
```
[the remark this answers is not in the document]
Comment (medvednikov) [reply vlib/v/ast/table.v:538]: Fixed in 8b677b1a39. Wrapped function returns now require identical `fn_type_signature` values (the same signature C codegen uses for Option/Result struct names) in addition to structural ABI compatibility. Added a checker error fixture for `?AliasedMathOp` versus `?MathOp`; the original same-alias `?MathOp` regression still passes under Clang `-cstrict`.

File: vlib/v/tests/interfaces/interface_method_fn_type_alias_return_test.v [hunk 2]
```diff
@@ -28,6 +28,10 @@ interface FactoryCalculator {
 	get_factory() MathFactory
 }
 
+interface OptionalCalculator {
+	get_operation() ?MathOp
```
[the remark this answers is not in the document]
Comment (medvednikov) [reply vlib/v/tests/interfaces/interface_method_fn_type_alias_return_test.v:34]: Fixed in 3bfdff1b77. The interface still returns `?MathOp`, while `OptionalSimpleCalc.get_operation` now returns a separately materialized `?EquivalentMathOp` with the same function signature, so the regression reaches the wrapped function compatibility path. The focused test also passes with `-cstrict -cc clang`.

File: vlib/v3/tests/interface_return_alias_compatibility_test.v [hunk 3]
```diff
@@ -34,6 +34,21 @@ fn test_interface_method_return_only_accepts_alias_equivalence() {
 	assert alias_run.exit_code == 0, alias_run.output
 	assert alias_run.output.trim_space() == '42', alias_run.output
 
+	wrapped_fn_compile := compile_interface_return(v3_bin, 'wrapped_fn_alias',
+		'type MathOp = fn (int, int) int\n\ninterface Calculator {\n\tget_operation() ?MathOp\n}\n\nstruct SimpleCalc {}\n\nfn (s SimpleCalc) get_operation() ?MathOp {\n\treturn fn (a int, b int) int {\n\t\treturn a + b\n\t}\n}\n\nfn main() {\n\tcalc := Calculator(SimpleCalc{})\n\toperation := calc.get_operation() or { panic("missing operation") }\n\tprintln(operation(2, 3))\n}\n')
```
[the remark this answers is not in the document]
Comment (medvednikov) [reply vlib/v3/tests/interface_return_alias_compatibility_test.v]: Fixed in 189e468ca1. V3 now unwraps aliases at the Option/Result payload boundary and accepts only underlying function types whose signatures remain exactly equal. The success fixture uses `?MathOp` versus distinct `?EquivalentMathOp`; the `MyInt` component-alias mismatch and numeric return mismatches still fail. The focused regression, all 6 V3 type tests, and the generated C under Clang `-Werror=incompatible-function-pointer-types` pass.
