### ISSUE TITLE
Compilation error when using `or {}` block on a variable of `result` type

### ISSUE THREAD

**Issue by lacikawiz** [vlang/v#17509]
### Describe the bug

A code using an `or {}` block on a `result` type does not compile but dies with a compiler bug error.

### Expected Behavior

See no compiler bug error and the code to run as expected

### Current Behavior

I get the following message when trying to compile/run:
```
/tmp/v_1000/json.17411427481542663655.tmp.c:12809: error: field not found: state
builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.
```

### Reproduction Steps

Save and compile/run the following code

```V
import json

struct Foo {
	x int
}

sfoos := '[{"x":123},{"x:456}]'
foos := json.decode([]Foo, sfoos)!
println(foos or {
	eprintln('boo-boo: {err}')
	return
})
```

### V version

V 0.3.3 15cb18c

### Environment details (OS name and version, etc.)

OS: linux, Linux Mint 20.3
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
CC version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

getwd: /home/laszlo/$TMP/2023-03/vtest
vmodules: /home/laszlo/.vmodules
vroot: /var/tmp/vlang
vexe: /var/tmp/vlang/v
vexe mtime: 2023-02-27 09:37:33
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.3 15cb18c

Git version: git version 2.25.1
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by Zhomart** [comment]
Try this:

```v
import json

struct Foo {
	x int
}

sfoos := '[{"x":123},{"x:456}]'
foos := json.decode([]Foo, sfoos) or {
	eprintln('boo-boo: ${err}')
	return
}
println(foos)
```

Works on `V 0.3.3 1a48d08`

<img width="257" alt="image" src="https://user-images.githubusercontent.com/830536/222944877-f51a14b6-8ade-4bef-a901-b851a43e8c7b.png">

**Comment by Zhomart** [comment]
V prints correct error message for your original example code:

<img width="574" alt="image" src="https://user-images.githubusercontent.com/830536/222944940-808a2cad-2672-41eb-a53c-a4a23617540e.png">

**Comment by thomas-mangin** [comment]
👋 @lacikawiz - with a recent V (using v up) my compiler does not report a C gen issue anymore and correctly reports the reason for the code to not work:
```sh
❯ v run xxx.v
xxx.v:9:9: error: cannot use `or {}` block on non-option variable
    7 | sfoos := '[{"x":123},{"x:456}]'
    8 | foos := json.decode([]Foo, sfoos)!
    9 | println(foos or {
      |         ~~~~
   10 |     eprintln('boo-boo: {err}')
   11 |     return
```

**Comment by lacikawiz** [comment]
That's good. I was using the V 0.3.3 with the pre-built V executable.
I did the update and I got the same result as you. So I guess, this can be closed.
