### ISSUE TITLE
Code examples in documentation don't work

### ISSUE THREAD

**Issue by enxoco** [vlang/v#2727]
**V version:** V 0.1.22 76c27c0
**OS:** Pop!_OS 18.10

**What did you do?**
```v
Tried the following code from the docs in the vlang playground
name := 'Bob'
println('Hello, $name!')  // `$` is used for string interpolation
println(name.len)
```
**What did you expect to see?**
3

 
**What did you see instead?**
redefinition of `name`
    1| name := 'Bob'

I just came across V randomly and it seems pretty cool but unfortunately, I am trying to follow along with the documentation and the code provided isn't working.  It works when I run it in the v prompt but not when I put it into a file and try to run it, or when I try to run it in the playground.

**Comment by enxoco** [comment]
Wow nevermind.  Just remembered that their are no global variables and I have been trying to define these examples outside of a function.

**Comment by medvednikov** [comment]
@enxoco this is a bug in V.

These example should work without `fn main()`, but they currently don't

I've just fixed the docs page  half an hour ago, it now adds `fn main() {` automatically before the code is sent to the playground.

**Comment by enxoco** [comment]
@medvednikov Nice to know.  I just reloaded the page and tried clicking on run and it works.  I was actually just in the process of forking the docs and adding fn main() to the examples.  Would that be helpful or no?

**Comment by medvednikov** [comment]
No need, this bug will be fixed soon.

In the meantime, the docs examples work.

**Comment by ka-weihe** [comment]
Works in V 0.1.26 50a8373.

**Comment by Ivo-Balbaert** [comment]
name := 'Bob'
println('Hello, $name!')  // `$` is used for string interpolation
println(name.len)

This code now gives (v 0.1.27) as output:

Hello, Bob!
3

on Windows 10, Ubuntu 20 and the Playground, so I think it can be closed.
