### ISSUE TITLE
checker: `!` in a `test_` fn of an architecture-qualified test file (`foo_test.arm64.v`) is rejected

### ISSUE THREAD

**Issue by quaesitor-scientiam** [vlang/v#28736]
## Describe the bug

An architecture-qualified test file (`foo_test.amd64.v`, `foo_test.arm64.v`) is compiled as a test by the driver, but the checker does not treat it as one: a `test_` fn in it cannot use `!`.

`pref.is_test_file_for_platform` (used by the driver to set `prefs.is_test`) accepts the `foo_test.<arch>.v` spelling, but `types.is_c_backend_test_file` — which `current_fn_is_test()` uses to decide whether `!` is allowed in a `test_` fn — only accepts `_test.v`, `_test.vv` and `_test.c.v`. `transform.is_void_test_propagation` and `markused.markused_file_is_test` have their own, equally narrow, copies.

The predicate was introduced in 2a7447b5e5. It is latent on master because the existing arch-qualified tests under `vlib/v/slow_tests/assembly/` do not use `!`; the new tests in #28449/#28453 do, and fail with it.

On macOS/Linux this is masked one level down: the V3 failure triggers the V 0.5.2 fallback, which compiles the file fine unless it uses something 0.5.2 does not know (such as `asm ... raw`), in which case the fallback's own parse error is what the user sees.

## Reproduction Steps

```v
// arch_test.amd64.v  (or .arm64.v on an arm64 host)
import strconv

fn test_propagation() {
	value := strconv.atoi('42')!
	assert value == 42
}
```

```
v test arch_test.amd64.v
```

Renaming the same file to `arch_test.v` makes it pass.

## Expected Behavior

`test_` fns in `foo_test.<arch>.v` behave exactly like in `foo_test.v`; the file is a test for every compiler stage, not just the driver.

## Current Behavior

```
arch_test.amd64.v:5:29: error: to propagate the Result call, `test_propagation` must return a Result
    3 |
    4 | fn test_propagation() {
    5 |     value := strconv.atoi('42')!
      |                                ^
```

## Possible Solution

Have `types.is_c_backend_test_file`, `transform.is_void_test_propagation` and `markused.markused_file_is_test` defer to `pref.is_test_file_for_backend`, so there is a single definition of "test file". PR to follow.

## Additional Information/Context

Found while running the arm64 SIMD tests from #28453 on an M5 MacBook: V3 failed, fell back to 0.5.2, and 0.5.2 reported `unexpected name 'raw'`.

## V version

V 0.5.3 01a8af9 (master, 2026-09-18)

## Environment details

Windows 11 amd64 and macOS arm64 (M5); same result with `v test` and with a direct `v -o ... foo_test.arm64.v`.
