### ISSUE TITLE
Example compilation error

### ISSUE THREAD

**Issue by SewerynKaminski** [vlang/v#16511]
### Describe the bug

Wheather example compilation error (examples/get_weather/get_weather.v)

### Expected Behavior

Compilation example without errors

### Current Behavior
```
==================
<artificial>:(.text+0x71d3): undefined reference to `cJSON_GetErrorPos'
collect2: error: ld returned 1 exit status
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```
### Reproduction Steps

./v -prod examples/get_weather/get_weather.v

### V version

V 0.3.2 7c7ebd6

### Environment details (OS name and version, etc.)

OS: linux, Ubuntu 22.04.1 LTS 
Processor: 16 cpus, 64bit, little endian, AMD Ryzen 7 3700X 8-Core Processor 
CC version: cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

**Comment by thomaspeissl** [comment]
I guess this is caused by the used CC.
For me the example works on Termux and Ubuntu 22.10 (both with clang as CC).
Can you try installing clang and test again?
`v doctor ` should then show something like `CC version: Ubuntu clang version 15.0.2-1`

**Comment by JalonSolov** [comment]
On Linux, with latest V and `gcc (GCC) 12.2.0`:
```
$ v -prod examples/get_weather/get_weather.v
$ ./examples/get_weather/get_weather
未来两小时天气:
未来两小时不会有雨。出门佩戴口罩，保障您和家人健康.
$
```

**Comment by SewerynKaminski** [comment]
I have deleted local repo and try clean build of V.  It's fine now :)
