### ISSUE TITLE
the interface sample code reports error

### ISSUE THREAD

**Issue by lydiandy** [vlang/v#3514]
**V version:** V 0.1.24 9b3ac7e
**OS:**  mac

**What did you do?**
interface sample code:
`
module main

struct Dog {}

struct Cat {}

fn (d Dog) speak() string {
	return 'woof'
}

fn (c Cat) speak() string {
	return 'meow'
}

interface Speaker {
	speak()string
}

fn perform(s Speaker) {
	println(s.speak())
}

fn main() {
	dog := Dog{}
	cat := Cat{}
	perform(dog) // "woof"
	perform(cat) // "meow"
}
`

**What did you expect to see?**

no error
**What did you see instead?**
2 warnings and 1 error generated.V error: C error. This should never happen. 
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by requnix** [comment]
For some extra context when running the above:

**V version:** V 0.1.25 01f45f0
**OS:** macOS Catalina 10.15.2

```
~ v run  -cg speaker.v
C compiler=cc
/private/var/folders/pw/k47jjv757gb4lq43582dqc000000gn/T/v/speaker.tmp.c:4248:72: error: extraneous ')' before ';'
 ((string (*)())(Speaker_name_table[s._interface_idx][0]))(s._object ) ) ;
                                                                       ^~
/private/var/folders/pw/k47jjv757gb4lq43582dqc000000gn/T/v/speaker.tmp.c:4251:18: warning: excess elements in struct initializer
Dog dog= (Dog) { EMPTY_STRUCT_INITIALIZATION } ;
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/pw/k47jjv757gb4lq43582dqc000000gn/T/v/speaker.tmp.c:112:37: note: expanded from macro 'EMPTY_STRUCT_INITIALIZATION'
#define EMPTY_STRUCT_INITIALIZATION 0
                                    ^
/private/var/folders/pw/k47jjv757gb4lq43582dqc000000gn/T/v/speaker.tmp.c:4252:18: warning: excess elements in struct initializer
Cat cat= (Cat) { EMPTY_STRUCT_INITIALIZATION } ;
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/pw/k47jjv757gb4lq43582dqc000000gn/T/v/speaker.tmp.c:112:37: note: expanded from macro 'EMPTY_STRUCT_INITIALIZATION'
#define EMPTY_STRUCT_INITIALIZATION 0
                                    ^
2 warnings and 1 error generated.
V error: C error. This should never happen.
```

**Comment by eyelash** [comment]
The code above now works with V 0.1.27.
