### ISSUE TITLE
[regression] Compiler error when using same V variable name as a C struct / typedef

### ISSUE THREAD

**Issue by Larpon** [vlang/v#18743]
The attached MRE used to compile and run without errors.

**V doctor:**
```
V full version: V 0.4.0 44a6741.329e063
OS: linux, "EndeavourOS Linux"
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz

getwd: /home/lmp/Projects/vdev/v_var_name_bug
vexe: /home/lmp/Projects/v/v
vexe mtime: 2023-07-02 12:23:08

vroot: OK, value: /home/lmp/Projects/v
VMODULES: OK, value: /home/lmp/.vmodules
VTMP: OK, value: /dev/shm/v_1000

Git version: git version 2.41.0
Git vroot status: 0.4-10-g329e0637
.git/config present: true

CC version: cc (GCC) 13.1.1 20230429
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg bug.v`
```v
import ma

fn main(){
 	ma_engine := &ma.Engine{}
 	dump(ma_engine)
 	// THIS works:
 	// engine := &ma.Engine{}
	// dump(engine)
}

```

**What did you expect to see?**

Successful compile and output from `dump()`

**What did you see instead?**
```
==================
/dev/shm/v_1000/bug.6941884807437322102.tmp.c:12566: error: identifier expected
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

```

Minimal reproducible example (with module + C code):
[v_var_name_bug.zip](https://github.com/vlang/v/files/11929484/v_var_name_bug.zip)
Just unzip and `cd v_var_name_bug && v run .` to see the error

**Comment by spytheman** [comment]
Bisecting shows that it regressed in 83ee2827d400e6661fb3ce64922673cd240b7722 for some reason.
@felipensp can you please take a look, when you have time?

**Comment by spytheman** [comment]
The diff between the code generated before 83ee2827d400e6661fb3ce64922673cd240b7722 and after it is this:
```diff
<       ma__Engine* ma_engine = ((ma__Engine*)memdup(&(ma__Engine){EMPTY_STRUCT_INITIALIZATION}, sizeof(ma__Engine)));
---
>       ma__Engine* ma_engine = ((ma_engine*)memdup(&(ma_engine){EMPTY_STRUCT_INITIALIZATION}, sizeof(ma_engine)));
```

**Comment by Larpon** [comment]
Thanks @spytheman
