### PR TITLE
tools: fix vsymlink build on Windows (explicit u32 casts for C API args)

### PR DESCRIPTION
**Pull request by mynameisbreak**
Fixes the `v symlink` build failure reported in #28821 (call-site hotfix only).

## Problem

`cmd/tools/vsymlink/vsymlink_windows.c.v` no longer compiles on Windows:

```
vsymlink_windows.c.v:171:49: error: cannot use `int` as `u32` in argument 4 to `C.RegSetValueExW`
vsymlink_windows.c.v:182:46: error: cannot use `int` as `u32` in argument 2 to `C.SendMessageTimeoutW`
vsymlink_windows.c.v:183:39: error: cannot use `int` as `u32` in argument 5 to `C.SendMessageTimeoutW`
vsymlink_windows.c.v:159:70: warning: casting voidptr to `&u8` is only allowed in `unsafe` code
```

`os.wm_settingchange` / `os.smto_abortifhung` (cross-module consts) and `C.REG_EXPAND_SZ`
(C macro) are typed `int`, while the C bindings in `vlib/builtin/cfns.c.v` declare those
parameters as `u32`. Untyped literals still coerce; named `int` constants do not.

## Change

- wrap `&u8(reg_value.data)` in `unsafe` (silences the voidptr cast warning)
- cast `C.REG_EXPAND_SZ`, `os.wm_settingchange`, `os.smto_abortifhung` to `u32(...)` at the call sites

## Verification

On Windows 11 x64, `V 0.5.2 63c15de`:

```
v -o vsymlink_test.exe cmd/tools/vsymlink
```

compiles with no errors and no warnings. Temp binary removed after the check.

## Note

This is a **workaround at the call site**, not a fix for the underlying compiler regression
described in #28821 (cross-module / C-macro integer constants should coerce to `u32` again).
Landing this unblocks `v symlink` in the meantime.

### CODE REVIEW

**Review by medvednikov — COMMENTED** [review]
Reviewed at `a88aaef30739fda8e8279be6ab88b41981b2cd54`.

No actionable correctness issue found in this call-site hotfix. I checked the affected declarations in `vlib/builtin/cfns.c.v`: the registry value type, message ID, and timeout flags are all `u32` parameters, so the three explicit conversions are consistent with the bindings. The `unsafe` block is limited to the existing byte-pointer view of the allocated `[]u16` buffer; it does not alter allocation size, ownership, or the registry read length.

UTF-16 termination/byte counts, registry error handling, and the broadcast timeout are unchanged. This addresses the tool's affected call sites, not the broader constant-coercion behavior described in the linked issue.

Validation: complete diff and binding-level source review only. I did not reproduce the Windows build or execute the tool because no V compiler is available locally. CI status and results were not considered.
