### ISSUE TITLE
cannot register struct `Stdio`, another type with this name exists

### ISSUE THREAD

**Issue by leighmcculloch** [vlang/v#10012]
It appears that vls does not compile with the current v master (0.2.2 9d4783a).

```
.../vls/cmd/vls/stdio.v:11:8: error: cannot register struct `Stdio`, another type with this name exists
    9 | fn C.fgetc(stream byteptr) int
   10 | 
   11 | struct Stdio {
      |        ~~~~~
   12 | pub mut:
   13 |     debug bool
```

**Comment by scorwin** [comment]
This is very late, but I have just found that this error occurs when you make a copy of `mymodule.v` in the same directory (probably as a temporary backup).  Remove the copy, or other code that defines the object, and Bob's your uncle.  This is undoubtedly due to a feature of the build system that I don't yet understand.  Perhaps it is also already noted in the docs, but if so, I missed it.
