### PR TITLE
checker: fix generic struct init with update expr (fix #17824)

### LINKED ISSUE #17824: generic struct initalisation regression after 90591eb81
### Describe the bug

```
/v/misc/bugs/t.v:17:12: error: generic struct init must specify type parameter, e.g. Foo[T]
   15 | 
   16 | pub fn (t Transform[T]) clone() Transform[T] {
   17 |     return Transform[T]{
      |            ~~~~~~~~~~~~~
   18 |         ...t
   19 |     }
```

### Expected Behavior

The program should compile and run cleanly.

### Current Behavior

It triggers a checker error.

### Reproduction Steps

```v
module main

pub struct Time[T] {
pub mut:
    start T
    end   T
}

pub struct Transform[T] {
pub mut:
    time   Time[T]
    before []T
    after  []T
}

pub fn (t Transform[T]) clone() Transform[T] {
    return Transform[T]{
        ...t
    }
}

fn main() {
    a := Transform[f64]{
        before: [0.0, 0.0]
        after: [320.0, 240.0]
    }

    b := a.clone()

    println(b)
}
```

### Possible Solution

The checker error should be more specific, so that it does not trigger for this case.
If I comment out `vlib/v/checker/struct.v:300`, then that program compiles and runs.

### Additional Information/Context

_No response_

### V version

V 0.3.3 4ef6e16

### Environment details (OS name and version, etc.)

Ubuntu 20.04 LTS

### PR DESCRIPTION
**Pull request by yuyi98**
This PR fix generic struct init with update expr (fix #17824).

- Fix generic struct init with update expr.
- Add test.

```v
pub struct Time[T] {
pub mut:
	start T
	end   T
}

pub struct Transform[T] {
pub mut:
	time   Time[T]
	before []T
	after  []T
}

pub fn (t Transform[T]) clone() Transform[T] {
	return Transform[T]{
		...t
	}
}

pub fn (t Transform[T]) default() Transform[T] {
	return Transform[T]{}
}

fn main() {
	a := Transform[f64]{
		before: [0.0, 0.0]
		after: [320.0, 240.0]
	}

	b := a.clone()
	println(b)
	assert b.before == a.before
	assert b.after == a.after

	c := a.default()
	println(c)
	assert c.before.len == 0
	assert c.after.len == 0
}

PS D:\Test\v\tt1> v run .
Transform[f64]{
    time: Time[f64]{
        start: 0.0
        end: 0.0
    }
    before: [0.0, 0.0]
    after: [320.0, 240.0]
}
Transform[f64]{
    time: Time[f64]{
        start: 0.0
        end: 0.0
    }
    before: []
    after: []
}
```

### CODE REVIEW

File: vlib/v/checker/struct.v [hunk 1]
```diff
@@ -648,8 +648,9 @@ fn (mut c Checker) struct_init(mut node ast.StructInit, is_field_zero_struct_ini
 							node.pos)
 					}
 				}
-				if !field.has_default_expr && field.name !in inited_fields && !field.typ.is_ptr()
-					&& !field.typ.has_flag(.option) && c.table.final_sym(field.typ).kind == .struct_ {
+				if !node.has_update_expr && !field.has_default_expr && field.name !in inited_fields
+					&& !field.typ.is_ptr() && !field.typ.has_flag(.option)
+					&& c.table.final_sym(field.typ).kind == .struct_ {
```
Comment (spytheman) [inline vlib/v/checker/struct.v:653]: I expected, the fix would be around `vlib/v/checker/struct.v:300` 🤔 . 
However it does with the PR, so good work.

**Comment by spytheman** [comment]
`return Transform[T]{}` in `clone()` will still trigger the same error.

**Review by spytheman — APPROVED** [review]
