### ISSUE TITLE
v test does not forward -enable-globals to the test compilations (0.5.2)

### ISSUE THREAD

**Issue by Mintormo** [vlang/v#28671]
### Describe the bug

`v -enable-globals test some_test.v` does not pass `-enable-globals` down to the
per-file test compilation, so every test file that uses `__global` fails with
`error: use \`v -enable-globals ...\` to enable globals`.

Passing the same flag through the `VFLAGS` environment variable works, so the
flag itself is fine — it is just not forwarded by `v test`.

Our test suite (15 files of a GUI library that keeps its object registries in
`__global`) is run with exactly this command line and started failing with this
error after we upgraded to 0.5.2; switching the flag to `VFLAGS` fixed it.

### Reproduction Steps

`bug_test.v`:

```v
__global g_counter = 0

fn test_global() {
	g_counter++
	assert g_counter == 1
}
```

```
$ v -enable-globals test bug_test.v
---- Testing... ----------------------------------------------------------------
V compilation failed (compiler_error); retrying with `~/.cache/v/v1-fallback/0.5.2/v`.
bug_test.v:1:1: error: use `v -enable-globals ...` to enable globals
    1 | __global g_counter = 0
      | ~~~~~~~~~~~~~~~~~~~~~~
FAIL     0.000 ms bug_test.v
Summary for all V _test.v files: 1 failed, 1 total.
```

Note the hint `v test` prints for the failure, which also drops the flag:

```
To reproduce just failure 1 run:    '/home/igor/soft/v/v'  'bug_test.v'
```

### Expected Behavior

`v -enable-globals test bug_test.v` compiles and runs the test, as
`VFLAGS="-enable-globals" v test bug_test.v` does:

```
$ VFLAGS="-enable-globals" v test bug_test.v
OK       2.276 ms bug_test.v
Summary for all V _test.v files: 1 passed, 1 total.
```

### Current Behavior

The test file is compiled without `-enable-globals` and fails to build.

### Possible Solution

Forward `-enable-globals` (and presumably the other compiler flags given before
the `test` command) to the child compilations, and include them in the
"To reproduce just failure N run:" hint.

### V version

V 0.5.2 7cbb67b

### Environment details (OS name and version, etc.)

Linux 7.0.0-31-generic x86_64, gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by medvednikov** [comment]
Please confirm it's been fixed for you.
