### ISSUE TITLE
parser: nested `unsafe` diagnostic (550f6cb843) lacks V1's `defer` exemption — `defer { unsafe { … } }` inside `unsafe` is a hard error

### ISSUE THREAD

**Issue by quaesitor-scientiam** [vlang/v#28802]
Sub-issue of #28447 (it blocks building master on Windows, where that roadmap's PRs are verified).

**Describe the bug**

Since 550f6cb843 (`parser: diagnose nested unsafe blocks`, 2026-09-19) the parser reports `already inside `unsafe` block` for `vlib/os/os.c.v:626`, which is inside the `$if windows` branch of `os.get_raw_line`:

```v
		unsafe {
			initial_size := 256 * wide_char_size
			mut buf := malloc_noscan(initial_size)
			defer { unsafe { buf.free() } }
```

The inner `unsafe` was added on purpose by e96355aca5 (2025-08-26, "os: eliminate warning for `v -cross -o vc/v.c cmd/v` on linux"): the established checker validates a `defer` body outside the enclosing `unsafe` context, so `buf.free()` needed its own block there. The new parser diagnostic treats the same code as an error, so a compiler built from master cannot compile anything that imports `os` for a Windows target — including `cmd/v` itself and every `cmd/tools/` program.

**Reproduction Steps**

On Linux (WSL2, x86_64), with a compiler built from master:

```
$ printf 'import os\nfn main() { println(os.getwd()) }\n' > /tmp/uses_os.v
$ ./v -os windows -check /tmp/uses_os.v
vlib/os/os.c.v:626:12: error: already inside `unsafe` block
```

`git bisect` between 2b99da47ea (good) and 3186f8d6fa (bad) with that command names 550f6cb843 as the first bad commit; head 9f29ea6c1d still fails. `./v -os linux|macos|freebsd -check cmd/v` are clean at 9f29ea6c1d, so only Windows targets are affected.

On Windows 11 amd64 the same shows up as soon as the new compiler is used: `v.exe` at 2b99da47ea builds `cmd/v` from 3186f8d6fa fine, but the resulting `vnew.exe test <dir>` fails while compiling `cmd/tools/vtest.v` with the same `vlib/os/os.c.v:626:12` error, so `v self`/tool builds are broken there.

**Expected Behavior**

vlib compiles for Windows targets. Either the diagnostic should not fire for an `unsafe` block that opens inside a `defer` body (the defer body is validated in its own context, which is why the inner block exists), or `os.c.v` needs a form both compilers accept.

**Current Behavior**

Hard error at `vlib/os/os.c.v:626:12` for every Windows-target compilation that imports `os`.

**Possible Solution**

Reset `unsafe_depth` while parsing a `defer` body (the way `defer_depth` is tracked), so `defer { unsafe { ... } }` stays legal inside an `unsafe` block; or drop the inner block in `os.c.v` if the established compiler no longer needs it.

**V version:** V 0.5.2 9f29ea6
**Environment details:** WSL2 Linux x86_64 (bisect, `-os windows`); Windows 11 Pro 10.0.26200 amd64 (tool build failure)

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by quaesitor-scientiam** [comment]
Fixed by #28803 (239f06c1de): `os.c.v` now uses `defer { buf.free() }`. Verified with a compiler built from 239f06c1de on Linux: `./v -os windows -check` is clean for a program importing `os` and for `cmd/v`. Closing.

**Comment by quaesitor-scientiam** [comment]
Reopening, refocused: #28803 fixed vlib's instance, but the diagnostic itself still diverges from the established compiler.

The V1 parser had the same error with an explicit exemption for `defer` bodies (`vlib/v/parser/parser.v:4910` at 2a7447b5e5^):

```v
if p.inside_unsafe && !p.inside_defer {
	err := p.error_with_pos('already inside `unsafe` block', pos)
```

That exemption exists because V1's checker validates `defer` bodies at function exit, outside the enclosing `unsafe` context (`vlib/v/checker/fn.v:996` at the same commit), so `defer { unsafe { ... } }` inside an `unsafe` block was the required warning-free form — which is exactly why e96355aca5 wrote `os.c.v` that way. 550f6cb843 ported the diagnostic without the `!inside_defer` condition, so any user code written the V1 way is now a hard error in V3, and there is no spelling that is warning-free on V1 and accepted by V3.

Suggested fix: skip the diagnostic (or reset `unsafe_depth`) while parsing a `defer` body, matching V1, with a fixture for `unsafe { defer { unsafe { f() } } }`.

**Comment by quaesitor-scientiam** [comment]
Closing again: with V1 removed from the tree, V3's rule is the reference, and #28803 resolves the V3 side (vlib builds for Windows targets; `defer { buf.free() }` inside `unsafe` is accepted). The V1-parity note above is informational only.
