### ISSUE TITLE
Example for "testing" does not compile

### ISSUE THREAD

**Issue by shnorbluk** [vlang/v#6461]
**V version:** 0.1.29
**OS:** Linux

**What did you do?**
I created the files hello.v and hello_test.v, as written in the "Testing" section of the documentation

**What did you expect to see?**
Test passed
 
**What did you see instead?**
hello_test.v:2:12: error: unknown function: hello

**Comment by JalonSolov** [comment]
Nifty.  I get the same error with the latest version of V.

**Comment by shnorbluk** [comment]
Thank you for your quick fix, but it does not compile with latest v (0.1.29 ae48b70). I get the same compile error, even after adding the pub keyword. 
I found a workaround by putting hello.v in a module and importing the module in hello_world_test.v , but is it required or is it a bug?
And is it intentional to only allow public code to be testable in unit tests?
Thank you.

**Comment by shnorbluk** [comment]
Hi! Can you please reopen this issue as it is not fixed. I cannot do it myself. Thank you.

**Comment by JalonSolov** [comment]
I can confirm that the test code as given in the documentation still does not work.  After copy/paste of `hello.v` and `hello_test.v`, when I try to run the test it fails:
```
jalon@Ripper:~$ v hello_test.v
hello_test.v:2:9: error: unknown function: hello
    1 | fn test_hello() {
    2 |     assert hello() == 'Hello world'
      |            ~~~~~~~
    3 | }
    4 |
jalon@Ripper:~$
```

**Comment by JalonSolov** [comment]
As a naive attempt to fix the code, I added `module main` at the top of both files, and get this error instead
```
jalon@Ripper:~$ v hello_test.v
hello.v:3:1: warning: function `hello` in module main cannot be declared public
    1 | module main
    2 |
    3 | pub fn hello() string {
      | ~~~~~~~~~~~~~~~~~~~~~
    4 |     return 'Hello world'
    5 | }
jalon@Ripper:~$
```

**Comment by JalonSolov** [comment]
So then I removed the `pub` as the error suggested, and now, finally it appears to work with the files as follows
```
// hello.v
module main

fn hello() string {
        return 'Hello world'
}
```
```
// hello_test.v
module main

fn test_hello() {
        assert hello() == 'Hello world'
}
```

**Comment by JalonSolov** [comment]
From this I deduce that a `module` statement appears to be _required_ for the tests to work.  If this is correct, then it should be documented as such.  Otherwise the necessity of having the `module` statement is the problem.

**Comment by spytheman** [comment]
`module xyz` is required for the internal module testing of any module, including `main`, yes (internal in the sense that the test is compiled as part of the same module, and so does not need to import the tested code).

**Comment by JalonSolov** [comment]
So if neither file has a `module` statement, it treats them as being in separate modules?  I thought `module main` was the default if an explicit `module` was not specified.

**Comment by spytheman** [comment]
The module declaration is needed for a test to be considered as internal (part of the same module).

**Comment by spytheman** [comment]
I've updated the testing section https://github.com/vlang/v/blob/master/doc/docs.md#test-files in 9610261.

**Comment by JalonSolov** [comment]
Thanks for correcting the test docs.

**Comment by shnorbluk** [comment]
Yes it works. Thank you.
You can even omit the `module main` in hello.v, which is implicit, but not in hello_test.v. This makes sense, as test files are external test unless having explicit `module` statement.
